#!/usr/bin/python
# -*- coding: utf-8 -*-

dictId2Desc = {
#0-9
'26607604':'Die Reportagereihe mit Reinhold Beckmann beleuchtet politische und gesellschaftliche Ereignisse.',
'31938368':'In #EinMomentDerBleibt schildern Flüchtlinge zum ersten Mal überhaupt ihre bewegende Geschichte.',
'16888632':'Die interaktive Late Night zur Bundestagswahl',
'15918032':'103.7 UnserDing - Das Jugendradio des Saarländischen Rundfunks zeigt regelmäßig coole Clips für junge Menschen.',
'29503360':'Esther und André erkunden die 16 Bundesländer',
'8638714':'In der Sendung gibt es eine klare Arbeitsteilung: Manuel Andrack ist dafür zuständig, ausgesuchte Lebensmittel zu kaufen - am besten direkt vom Erzeuger - und Sternekoch Harald Rüssel verwandelt sie in köstliche Gerichte.',
'26009346':'In der Kabarett-WG treffen messerscharfes Politik-Kabarett auf Comedy und Sitcom, Leidenschaft auf verkifftes Phlegma, Analyse auf pure Emotion.',
'17399976':'Wählen Sie Ihren Favoriten. Der rbb sucht die 30 tollsten, größten, besten, schönsten ... Ihre Stimme zählt.',
'967542':'Einmal monatlich freitags um 22.00 Uhr (nach 9!) talken Judith Rakers und Giovanni di Lorenzo live im Dritten (3!) mit prominenten Köpfen aus Kultur, Wissenschaft, Politik und Sport. Immer dabei: Spektakuläre Live-Musik von Barock bis Heavy Metal.',
'13376662':'Vom 25. bis 29.3. dreht sich beim SWR alles um die Krise in der Lebensmitte. Alle Sendungen zur Midlife Crisis, ob Dokumentationen, Spielfilme oder die Sendezeiten der Serie "Zeit der Helden", finden Sie in unserer Übersicht. Hier verpassen Sie keinen Termin.',
'12772246':'45 Min zeigt Filme über spannende Themen, die Menschen im Norden bewegen. Die Doku-Reihe findet überraschende Antworten auf Fragen, die sich im Alltag stellen.',
'14049104':'Für uns von "7 Tage..." ist das Leben eine Herausforderung und ein Abenteuer. Wir beobachten und begleiten diese Menschen, nehmen teil, leben in ihrem Leben.',
'14913046':'Die 10-teilige Doku-Serie "1 x 1 der Wirtschaft" beschreibt spannend, witzig und fundiert, wie Wirtschaft entstand und wie sie funktioniert. In jeder der 15-minütigen Folgen erzählen prominente Experten aus der Praxis.',

#A
'3822076':'Die ABENDSCHAU hat den Berlin-Blick: Nah dran an den Menschen und ihren Geschichten – rau, aber herzlich. Täglich um 19:30 Uhr im rbb Fernsehen.',
'14913430':'Abendschau',
'14913448':'Abendschau - Der Süden',
'12882012':'Abenteuer Erde bietet Einblicke, veranschaulicht Zusammenhänge, macht Lust auf Expeditionen.',
'32325376':'Sie ist Polizistin und liebt ihren Beruf. Er auch. Das sind aber auch schon alle Gemeinsamkeiten der Kommissare Hundt und Katzer. Naja fast. Ein gemeinsame Tochter haben sie auch noch ...',
'743240':'Mit "aktuell" starten die Saarländerinnen und Saarländer in das Vorabendprogramm im SR Fernsehen.',
'8638772':'Fünf Minuten Nachrichten aus der Region informieren über die aktuellen Themen des Tages.',
'4040654':'"aktuell" steht für regionale und überregionale Infomation - kompakt. Ein Themenmix aus internationaler Politik bis hin zu den Ereignissen des Tages in der Region.',
'26837706':'"aktuell" steht für regionale und überregionale Information - kompakt. Ein Themenmix aus internationaler Politik und den Ereignissen des Tages in der Region. Täglich um 21:45 Uhr sowie sonntags um 22:05 Uhr.',
'743232':'Das regionale Infomagazin des SR mit Nachrichten und täglichem Sportblock - täglich im SR Fernsehen.',
'7293524':'Das Informationsmagazin im WDR Fernsehen',
'6513590':'Alfons - Kabarettist und Gastgeber in Personalunion.',
'15528234':'Kochen mit Bio',
'25679250':'Nordrhein-Westfalen im Fokus',
'26851714':'In der Serie bringt Sekretärin Klara Degen mit ihren unkonventionellen Ideen den Alltag von Hauptkommissar Kleinert gehörig durcheinander.',
'3416170':'Mittwochs um 21.00 Uhr im hr-fernsehen: Moderator Thomas Ranft erklärt komplexe Themen, die jeden betreffen. Eine Sendung für alle, die mehr wissen wollen.',
'3350202':'Die Wettersendung des Hessischen Rundfunks, werktäglich um 19.15 Uhr im hr-fernsehen. Informationen und Hintergründe rund um das Thema Wetter mit Moderator Thomas Ranft.',
'22399478':'Mehr als eine Million Menschen in Deutschland leiden an der Alzheimer-Krankheit. Der Begriff Alzheimer ist zum geflügelten Wort für Vergesslichkeit geworden. Weitgehend unbekannt dagegen ist der Mensch Alois Alzheimer, der diese Krankheit vor über hundert Jahren entdeckt hat.',
'14912506':'',
'14912932':'Campus macht Fernsehen für Studieninteressenten, Studierende, Lehrende und Forschende sowie für alle Menschen, die sich für die Hochschulszene interessieren. Campus schafft eine unabhängige Öffentlichkeit für die akademische Community.',
'32576090':'',
'14913860':'Das alpha-campus Magazin bietet Tipps und Informationen zum Studienalltag sowie Hintergrundinfos zu Forschung und Lehre an bayerischen Universitäten und Hochschulen - jeden Monat mit einem neuen Schwerpunkt-Thema.',
'24072178':'Das alpha-Campus MAGAZIN bietet Tipps für Studierende zu den Themen Studieren, Leben, Job & Karriere. Jeden Donnerstag um 19.00 Uhr.',
'14913006':'Gibt es Außerirdische? Wie dünn war die Ursuppe? Und wie sieht eigentlich die Zukunft des Universums aus? Manchmal wissen nur Experten wie der Astrophysiker Harald Lesch weiter.',
'14912942':'Im alpha-Forum kommen Persönlichkeiten aus Politik und Wirtschaft, Wissenschaft und Gesellschaft, Religion und Kultur in 45 Minuten ausführlich zu Wort.',
'29685242':'Zoogeschichten.',
'16030060':'Die Kulturshow mit Anke Engelke',
'25014972':'Anna macht sich auf die Suche nach wilden Tieren!',
'328454':'Anne Will diskutiert sonntags um 21.45 Uhr mit ihren Gästen über politische Prozesse, wirtschaftliche Zusammenhänge und gesellschaftliche Trends. Die Videos der vergangenen Sendungen finden Sie hier.',
'18112332':'Anselm Grün',
'428628':'',
'3304234':'Spezielle Sendungen zu aktuellen Anlässen und aktuelle Videoblogs der ARD-Korrespondenten.',
'24718452':'Die Tage vom 15. bis 21. November 2014 stehen in den ARD-Programmen ganz im Zeichen der Toleranz.',
'30922708':'Die ARD-Themenwoche zeigt vom 4. bis 10. Oktober die verschiedenen Aspekte der Heimat - im TV, im Radio und im Netz.',
'4040668':'Die Fußball-Sendung im SR Fernsehen.',
'27136742':'Fünf Jugendliche, ein idyllischer Pferdehof und ein großes Geheimnis.',
'7545220':'Das Kulturmagazin des MDR',
'14913342':'Asül für alle',
'11790164':'Großstadt-Reportagen intim und hautnah. Thomas bekommt die Aufgabe, in jeder Stadt, die er bereist, 3 Sofas zu finden. Also 3 Gastgeber, die ihn bei sich in der Wohnung übernachten lassen und die ihm ihre Lieblingsplätze, Bars und ihre Geheimtipps zeigen...',
'23414126':'Doku über das Unfallkrankenhaus Marzahn',
'7545164':'Vorgestellt werden Schmalspurbahnen in Sachsen, Sachsen-Anhalt und Thüringen und ihre Betreiber.',
'27670304':'Anja Koch, Reporterin und Moderatorin beim Sorbischen Programm des rbb, sucht nach wendischen Spuren. Dafür begibt sie sich in Orte in der brandenburgischen Niederlausitz, die zum sorbischen/ wendischen Siedlungsgebiet gehören.',
'8638724':'Ein Kommentar zum Zeitgeschehen, eine Meditation zu Passionsbildern, ein Film über die Kinderfreizeit einer Pfarrgemeinde oder die Kunstaktion an einem Kirchturm: "aus christlicher sicht" berichtet darüber, was Christen im Saarland bewegt und was sie auf die Beine stellen.',
'13165946':'gesucht und gefunden von Madeleine Wehle',

#B
'15447264':'Menschen-Reportage mit Bettina Böttinger',
'5651352':'',
'9602930':'Max Moor reist durch Brandenburg und trifft dort ansässige Künstler, Maler und Schriftsteller.',
'19060068':'Die fünfteilige Dokumentarreihe zeigt Höhepunkte und Erfolge, Siege und Niederlagen der Olympischen Spiele seit den 50er Jahren aus bayerischer Sicht.',
'22672202':'Bayern feiern',
'14912822':'Promikoch Fritz Häring trifft auf Menschen aus aller Welt und kocht mit ihnen gemeinsam internationale Spezialitäten aus ihrer Heimat, kombiniert mit bayerischen Gerichten.',
'14912558':'Hier geht es um "Bayern fühlen", "Bayern erleben", "Bayern spüren". Carolin Reiber ist einmal im Monat für Sie im Freistaat unterwegs, um Ihnen die schönsten Ecken zu zeigen.',
'14920860':'Elisabeth Rehm führt durch die Sendung "Bei uns dahoam", sie stellt Volksmusik, Tradition und Heimatkultur aus unterschiedlichen Regionen Bayerns vor.',
'7545308':'Ungewöhnliche Menschen, Dinge und Lebensweisen asus unserer Heimat im Portrait',
'5739838':'',
'17989552':'',
'340982':'Hintergründe, Berichte und Reportagen aus dem ARD-Hauptstadtstudio.',
'12224908':'Der Bericht aus Brüssel - die gute Mischung aus kritischem Blick und enthusiastischer Überzeugung.',
'6392536':'Bettina Rust live aus dem Berlinale-Studio im Berlinale-Palast.',
'1100786':'',
'26460566':'Tietjen und Bommes stehen für unterhaltsame und intensive Gespräche. Das Moderatoren-Duo ist offen für Experimente, führt humorvoll und schlagfertig durch ihre Talksendung.',
'33031968':'Die Erträge aus Bingo! kommen Projekten im Bereich des Natur- und Umweltschutzes zugute. In der Umweltlotterie sind also Teilnehmer und Natur gleichermaßen die Gewinner.',
'7545396':'Berge, Menschen, Abenteuer',
'14913164':'',
'1920542':'Eine Stunde Hintergründe, Analysen und aktuelle Interviews zum Sportgeschehen des Wochenendes. Die Kultsendung im Bayerischen Fernsehen - jetzt auch als Podcast zum Mitnehmen für unterwegs. Kultige Gäste, kultige Sprüche - immer dabei als MP3.',
'14913174':'Blickpunkt Sport Regional',
'4106':'Täglich um 19:55 Uhr: Aktuelles von der Frankfurter Börse. Wie steht der DAX? Was waren die Tops und die Flops des Tages?',
'3822126':'Brandenburg aktuell ist das rbb-Nachrichten-Magazin aus Brandenburg für Brandenburg, täglich um 19:30 Uhr im rbb Fernsehen.',
'1082266':'Aktuelle Nachrichten und Hintergründe zum Zeitgeschehen',
'18109440':'Brettl-Spitzen',
'14913410':'BR extra forscht nach den Ursachen, beleuchtet Hintergründe und erläutert die Konsequenzen des Geschehens. Mit Live-Schalten, Reportagen und Hintergrundberichten von den jeweiligen Brennpunkten geben wir  möglichst schnell einen umfassenden Überblick.',
'17396062':'Die besten Geschichten schreibt das Leben. "Brisant", das Boulevardmagazin des MDR, greift sie auf und erzählt sie: Luxus und Laster, Klatsch und Tratsch, Lust und Liebe, Show und Unterhaltung.',
'2673662':'Das Boulevard-Magazin im Ersten. Hier finden Sie ausgewählte Videobeiträge der Sendung.',
'14049112':'Das Bücherjournal präsentiert seit mehr als 30 Jahren Neues vom Büchermarkt: deutsche und internationale Romane und Sachbücher, vom Bestseller bis zum Geheimtipp.',
'11685336':'Literatursendung im rbb Fernsehen mit Max Moor',
'6841986':'Wir zeigen Ihnen die Gespräche von der ARD-Bühne auf der Buchmesse 2011.',
'3341190':'Der Fußball-Sonntag in der Zusammenfassung',
'2958612':'Regierungserklärungen, Debatten und mehr',
'14912486':'Einmal im Monat diskutiert Tilmann Schöberl mit Bürgern vor Ort über ein aktuelles Thema.',
'967552':'Das bewegt Bremen, Bremerhaven und das Umland - das Regionalmagazin greift das auf, worüber die Menschen in der Region sprechen. Hier gibt es politische Diskussionen, Berichte über gesellschaftliche Ereignisse, Reportagen aus dem Leben, kritische Interviews, Kultur und Musik. Auch der Sport kommt nicht zu kurz. Von Montag bis Freitag immer mit der Wochenserie. buten un binnen informiert und unterhält zum Feierabend.',
'6494936':'Bremen ist eine sportverrückte Stadt. Deshalb leistet sich Radio Bremen eine tägliche Sportsendung im Fernsehen. Aktuell, unterhaltsam und blitzschnell: buten un binnen | sportblitz - seit mehr als 20 Jahren! Von Montag bis Freitag um 6nach6. Alles Wichtige über Werder Bremen, Basketball und Eishockey aus Bremerhaven, prominente Studiogäste und aufstrebende Talente. Kurz, konsequent und kompetent: buten un binnen | sportblitz!.',
'6690994':'Die Sendung ist die Kompaktausgabe des Regionalmagazins um 19.30 Uhr. Hier erfahren Sie die wichtigsten Nachrichten und Themen des Tages aus Bremen, Bremerhaven und dem Umland. Damit Sie zum Feierabend wissen, was während des Tages passiert ist.',
'16978272':'Unsere Wetterfrösche sind täglich für Sie in der Region unterwegs und geben einen Ausblick auf das Wetter der kommenden Tage, berichten über außergewöhnliche Naturereignisse oder besondere Wetterlagen. Jeden Tag an einem anderen Ort, mit unterschiedlichen Gesprächspartnern oder überraschenden Geschichten. buten un binnen | wetter - so abwechslungsreich wie das Wetter selbst.',
'17864678':'In jeweils 15-minütigen Episoden machen sich Gert Heidenreich, Anne-Isabell Zils und Markus Fisher auf die Suche nach Textstellen, die die Kraft der biblischen Sprache und ihrer Botschaft spüren lassen.',
'14913390':'Der Bauernhoftester',
'14912952':'Bayerische Geschichte',
'28119756':'Mit einem bundesweit einzigartigen Schulwettbewerb ermitteln KI.KA und Das Erste die beste Klasse Deutschlands.',
'30652394':'',
'11421672':'unterhaltsamer Check der Lebensqualität von Berliner Bezirken und Brandenburger Landkreisen',
'26607604':'Die Reportagereihe mit Reinhold Beckmann beleuchtet politische und gesellschaftliche Ereignisse.',

#C
'14913352':'Capriccio. Donnerstags um 22.00 Uhr im Bayerischen Fernsehen.<br/>Die Welt der Kunst und Kultur zeigt das Magazin Capriccio.',
'33031960':'',
'27092622':'Sexy, respektlos und relevant!',
'14913438':'Darwin gewann seine Erkenntnisse über die Entstehung der Arten nicht am Schreibtisch, sondern bei der akribischen Beobachtung der Natur. Die Sendereihe "Charles Darwin" erzählt über sein abenteuerliches Leben und befragt Experten zu seinen revolutionären Theorien.',
'11526406':'Die Reihe zeigt spannende Dokumentationen für Kinder.',
'17250800':'Die Entdeckershow mit Tobias Krell.',
'19100642':'',
'10017896':'In der 15 minütigen Personality Show gibt\'s \'misheard lyrics\' zum Drauflosgrölen und Selberfalschverstehen, den ultimativ kompetenten \'gamecheck\', außerdem Werbeparodien am Rande des Nervenzusammenbruchs und natürlich neue Perlen der Synchronisationskunst von und mit coldmirror.',
'15355648':'Von Ladies Night bis Baustelle Deutschland - Comedy im WDR Fernsehen',
'18916210':'Hessens beste Comedians, zu Gast im hr-fernsehen.',
'25304236':'Comedy & Satire – die Videos zu den lustigsten Sendungen im Ersten',
'23547074':'Mit Julius Fischer und Christian Meyer',
'12877076':'Das Integrationsmagazin im WDR Fernsehen',

#D
'26437310':'"D\'viertl Stund" ist eine Nachrichten- und Magazin-Satire mit dem Schmidt Max, der in der Rolle eines eifrigen BR-Reporters vergangener Zeiten den digitalen Anschluss komplett verpasst hat.',
'7293532':'Willkommen bei daheim + unterwegs!',
'14913698':'Dahoam is Dahoam',
'12577900':'Die Oldie-Show mit Hartmut Schulze-Gerlach',
'33031952':'DAS! informiert täglich über das, was im Norden Gesprächsthema ist.',
'14913046':'Die 10-teilige Doku-Serie "1 x 1 der Wirtschaft" beschreibt spannend, witzig und fundiert, wie Wirtschaft entstand und wie sie funktioniert. In jeder der 15-minütigen Folgen erzählen prominente Experten aus der Praxis.',
'17864678':'In jeweils 15-minütigen Episoden machen sich Gert Heidenreich, Anne-Isabell Zils und Markus Fisher auf die Suche nach Textstellen, die die Kraft der biblischen Sprache und ihrer Botschaft spüren lassen.',
'12439650':'Musik, Stars, Events, Games, Kino und Trends - DASDING.tv zeigt, was Sache ist. Jede Woche volles Programm. Live. Laut. Lässig.',
'20985044':'',
'25983654':'Im Mutcamp in Südafrika stellen sich 6 Jugendliche ihren Ängsten. Es ist eine Reise die ihr Leben verändern soll.',
'12882028':'Das Quiz im WDR',
'9029008':'Dokuserie, deren Schauplatz die Tierrettungsstation Harnas am Rand der afrikanischen Kalahari-Wüste ist.',
'442936':'Kirche und Glaube im Ersten',
'4040676':'Daten der Woche - Der Wochenrückblick fur das Saarland.',
'8638748':'Die Sendung präsentiert Kurzurlaubsziele in Deutschland und Europa, über die man spricht. Armgard Müller-Adams und Michael Friemel gehen abwechselnd auf Entdeckungstour und spüren auch Reisetipps und Neuigkeiten auf, die noch nicht in jedem Reiseführer stehen.',
'3437388':'Das Landesmagazin aus Hessen, immer sonntags um 18.00 Uhr im hr-fernsehen. Wir sagen Ihnen, wie sich die Entscheidungen in Berlin und Wiesbaden auf unser Leben in Hessen auswirken.',
'28405866':'"Naa, was willst du mal werden?" - Solche Fragen können ganz schön nerven! Um so besser, wenn man einfach mal in einen echt spannenden Job reinschnuppern kann - und zwar so richtig. Wo das geht? Na, bei "Dein Traumjob"!',
'248886':'Absurd, schlagfertig, schräg, das ist SWR3 latenight mit Pierre M. Krause. Hier gibt\'s die lustigen Filmchen aus der Show als Abo: Pierre als Praktikant oder als ratloser Reporter - garantiert sinnfreie Zone!',
'14913016':'Der Physiker Harald Lesch und der Philosoph Wilhelm Vossenkuhl nehmen auf einer blauen Couch im Münchner "Museum für Abgüsse Klassischer Bildwerke" Platz, um im intensiven Gespräch auf die großen Denker des Abendlandes aufmerksam zu machen und ihre Ideen und Gedanken in verständlicher Weise zu vermitteln.',
'14913066':'In der Sendereihe "DENKRAUM" werden Themen der Zeit aus philosophischer Sicht erörtert und für ein breites Publikum interessant aufbereitet.',
'14913390':'Der Bauernhoftester',
'14912952':'Bayerische Geschichte',
'11421672':'unterhaltsamer Check der Lebensqualität von Berliner Bezirken und Brandenburger Landkreisen',
'7613208':'Hauswirtschaftsmeisterin Yvonne Willicks kämpft sich durch den Produkte-Dschungel im Haushaltsbereich.',
'23162708':'Dyslexie',
'14912892':'Seit über 50 Jahren beweist der Komödienstadel mit klarem Bekenntnis zu Dialekt und Heimatthemen, dass Volkstheater im Fernsehen ein zeitloses Genre ist.',
'14912962':'Als aufgeklärte Menschen wissen wir, dass wir von unserer Kultur geprägt sind - doch greifen diese Einflüsse wesentlich tiefer und weiter als wir denken. In der Sendereihe "Der lange Schatten von Kultur" hinterfragt der Ethnologe Frank Heidemann das Eigene und öffnet den Blick für das Fremde.',
'11992544':'Die Reportage-Reihe begleitet Menschen aus Berlin und Brandenburg, die ihre Lebenssituation verändern wollen oder müssen.',
'22876986':'Der Markencheck',
'22834010':'Mit dem Montags-Check im Ersten wollen wir dem gestiegenen Bedürfnis unserer Zuschauer nach Orientierung in einer immer unübersichtlicheren Alltagswelt Rechnung tragen.',
'9397858':'"Der Osten – Entdecke wo Du lebst"  stellt geheimnisvolle Orte vor und erzählt ungewöhnliche Geschichten vom Leben in Mitteldeutschland.<br/>Axel Bulthaupt nimmt die Zuschauer mit auf Entdeckungsreise durch ihre Heimat.',
'8758550':'',
'19673410':'',
'12882044':'Sternekoch Björn Freitag gibt handfeste Tipps für den Verbraucher und nie gesehene Einblicke in die Lebensmittelindustrie.',
'14049120':'Unterwegs mit "Knochenbrecher" Tamme Hanken: Er ist ein Pferde-Chiropraktiker und ein norddeutsches Original.',
'29931638':'Werden Sie Teil einer einmaligen Echtzeit-Doku im Ersten. Am 4. Oktober 2015 im Ersten und auf www.DasErste.de.',
'25710252':'Deutsche Landschaften, Städte, Inseln',
'14912972':'Feuer, Wasser, Erde und Luft hielten die alten Griechen für die Bausteine unserer Welt. Was sagt die moderne Wissenschaft dazu? Woraus besteht eigentlich die Welt? Harald Lesch geht dieser uralten Menschheitsfrage nach.',
'18922392':'Die beliebtesten Ausflugsziele, Berge, Sehenswürdigkeiten, Flüsse, Sportler, Schauspieler der Hessen - und vieles mehr.',
'28119756':'Mit einem bundesweit einzigartigen Schulwettbewerb ermitteln KI.KA und Das Erste die beste Klasse Deutschlands.',
'30652394':'',
'26111552':'',
'247338':'',
'27945360':'',
'30292384':'Die Kanzlei',
'11321236':'',
'13489530':'Serie',
'14912720':'Die Komiker bringen das Lebensgefühl der Bayern auf den Punkt: Hinterfotzig, schräg, krachert - aber sehr liebenswert. Constanze Lindner, Eva Mähl, Florian Simbeck und Uli Bauer bürgen für schrägen bayerischen Humor.',
'28898340':'Im beschaulichen bergischen Städtchen Oberbreitbach sorgt  Belinda Mommsen als Tierheilpraktikerin für Wirbel.',
'7825658':'Richling',
'30222028':'Eine fiktive Comedy-Serie über die echten Mockridges.',
'15713334':'',
'14049232':'Die 30minütige Reportage im Vorabendprogramm: über ungewöhnliche Menschen und ungewöhnliche Orte in Norddeutschland.',
'26460574':'Wunderbare Landschaften, faszinierende Tierwelten und spannende Menschen: die nordstory erzählt Geschichten aus dem Norden.',
'5556544':'Spannende Detektiv-Geschichten für Kinder',
'14913076':'Harald Lesch erklärt in acht Folgen die Physik Albert Einsteins – vom Photoeffekt über Schwarze Löcher, Gravitationslinien bis hin zur Bedeutung, die Einsteins Erkenntnisse für unser heutiges Leben haben.',
'32831688':'',
'16269336':'Reportagereihe zu aktuellen Themen in Berlin und Brandenburg',
'3856484':'Die Reportage ist nah dran an den Menschen im Norden, ihrem Alltag, mit allen Träumen und Wünschen, aber auch Sorgen und Nöten. Diese Sendereihe beobachtet und hört zu und lässt den Zuschauer die Geschichte miterleben.',
'22380564':'Lach- und Sachgeschichten für Fernsehanfänger',
'1458':'Die Sendung mit der Maus ... und dem Elefanten. Hier gibt es die vergangenen Sachgeschichten aus einem Maus-Jahr als Video.',
'22380500':'Lach- und Sachgeschichten mit der Maus und ihren Freunden',
'8739802':'Die Spur der Täter" ist mit der Kriminalpolizei Kapitalverbrechern auf den Fersen. Dabei geht es um die detailgetreue Rekonstruktion der Aufklärung von Morden und Überfällen.',
'7486242':'Die Sendereihe mit Dokumentationen aus dem In- und Ausland',
'22380484':'Die neue Ensemble-Comedy-Show im WDR',
'23022010':'Die ARD hat eines der größten Korrespondentennetze weltweit. Viele erzählenswerte Geschichten "schaffen" es aber nicht in die großen Sendungen. In ihren Videoblogs berichten unsere Korrespondenten über die kleinen Dinge des Lebens und die große Politik, über Ernstes und Skurriles, über besondere Rituale und alltägliche Gebräuche.',
'3011224':'',
'3011232':'',
'13618360':'Die Show mit dem Hund',
'11140718':'Die einzige Show im deutschen Fernsehen, die von einem Hund moderiert wird!',
'14847140':'Wurde das Dings auf dem Feld verwendet? Oder diente es gar der Befriedigung geheimer Lüste ...? Das prominente Rateteam rät, dass sich die Balken biegen, denkt sich aberwitzige und absurde Erklärungen aus, diskutiert und debattiert um die richtige Lösung.',
'4040684':'SR-Videoreporter berichten <br/>							am zweiten und  vierten Montag im Monat im Wechsel mit "SaarLorLüx". <br/>							18.50 bis 19.20 Uhr',
'53390':'Dittsche - Das wirklich wahre Leben. Auch als Video on Demand Kult!',
'12877116':'Freitagabend ist NRW-Zeit!',
'13980890':'Dokumentationen, Dokumentarfilme und Reportagen in Einsfestival',
'1105036':'',
'24831852':'Dokumentarfilm',
'17603862':'',
'26131780':'Dokumentionen und Reportagen im hr-fernsehen zu aktuellen wie auch historischen Themen.',
'3822114':'Dokumentationen, Reportagen und Features aus Berlin und Brandenburg',
'17603894':'',
'13401098':'Erstaunliches - Made in Germany',
'23538620':'Die Dokumentarfilmreihe des Bayerischen Rundfunks beschäftigt sich mit dem Wandel in den bayerischen Dörfern.',
'339944':'Romane und Sachbücher vorgestellt und unter die Lupe genommen. Die Videos zum Büchermagazin im Ersten finden Sie hier.',
'26009346':'In der Kabarett-WG treffen messerscharfes Politik-Kabarett auf Comedy und Sitcom, Leidenschaft auf verkifftes Phlegma, Analyse auf pure Emotion.',
'17399976':'Wählen Sie Ihren Favoriten. Der rbb sucht die 30 tollsten, größten, besten, schönsten ... Ihre Stimme zählt.',
'967542':'Einmal monatlich freitags um 22.00 Uhr (nach 9!) talken Judith Rakers und Giovanni di Lorenzo live im Dritten (3!) mit prominenten Köpfen aus Kultur, Wissenschaft, Politik und Sport. Immer dabei: Spektakuläre Live-Musik von Barock bis Heavy Metal.',

#E
'26725648':'Infos und Videos rund um die ECHO-Verleihung 2015.',
'12937906':'Jeden zweiten Dienstag zur besten Sendezeit setzt der MDR auf die Programmfarbe Wissenschaft. "Echt" taucht beispielsweise ab in die Tiefen der Meere, spürt plötzlichen Gedächtnisverlust auf, oder ist bei der Öffnung der Gruft der Medici Augenzeuge.',
'25753818':'',
'4995380':'',
'14912862':'Leichte Küche mit "Aha-Effekt": Der Koch-Newcomer Hans Jörg Bachmeier zeigt, wie es geht. Der niederbayerische Spitzenkoch beweist, wie schnell und einfach man gute Gerichte zaubern kann.',
'12994070':'Die Lieblingsrezepte von WDR-Koch Björn Freitag',
'11062302':'',
'7545364':'Das MDR-Erfindermagazin',
'16877148':'In der Reihe "Einigkeit und Recht und Freiheit" besucht Max Schmidt die Schaltzentralen der Politik und erklärt auf seine unvergleichliche Art, wie die politischen Institutionen funktionieren.',
'3540670':'Einsfestival - junges Programm für Erwachsene.',
'22222970':'"Ein Sommer in Brandenburg" ist ein heimatkundliches Roadmovie. Mit einem alten Robur-Bus (Baujahr 1987) geht es einen Sommer lang über Brandenburgs Straßen und Wege um Land und Leute zu erkunden.',
'11425004':'Jung ? wild ? digital: Ab 30. April sendet EinsPlus täglich vier Stunden junges Programm in der Primetime: montags bis sonntags von 20.15 Uhr bis 0.30 Uhr ? verlässlich und gut auffindbar.',
'15185012':'In EINSWEITERgefragt sind Leute zu Gast, die wirklich etwas zu sagen haben.',
'7293540':'Gespräch aus Düsseldorf und Berlin: Aktuelle Themen aus Politik, Wirtschaft und Gesellschaft',
'1100776':'Reise',
'7545276':'Geschichten aus dem Leipziger Zoo',
'8528318':'Geschichten aus dem Leipziger Zoo',
'33031944':'',
'10317598':'Packende und faszinierende Tier- und Naturaufnahmen im Ersten.',
'30384088':'In jeweils 45-minütigen Folgen erkunden hr-Autoren ihr Bundesland, stellen die schönsten Regionen und ihre Bewohner vor und werfen einen Blick auf das, was Hessen ausmacht. "Erlebnis Hessen" nimmt den Zuschauer mit auf eine Reise, die begeistert und neue Perspektiven auf Land und Leute bietet.',
'12882060':'Von Friesland bis Neuseeland: Interessante Reiseziele rund um den Globus.',
'20214138':'',
'3407050':'',
'14913722':'Et(h)ikette',
'14912534':'euroblick',
'342024':'Reportagen und Hintergrundberichte zu europäischen Themen.',
'9525092':'Alle Infos rund um den Wettbewerb sowie die Songchecks der teilnehmenden Künstler, dazu aktuelle Videos  zum 61. Eurovision Song Contest in Stockholm.',
'17603902':'',
'7545124':'Das Nachrichtenmagazin',
'7545348':'Aktuelle Reportagen und spannende Geschichten',
'3856516':'Faszinierender Alltag in der Savanne zwischen Löwen und Elefanten, gewaltige Sprünge mit Känguru und Co, nächtliche Begegnungen mit Kauz und Fuchs, ökologische Entdeckungsreisen in exotische Ferne und in die unbekannte Welt vor der eigenen Haustür.',
'9946790':'Expedition',
'3709210':'Christian Ehring zeigt den Irrsinn der Woche, immer bissig, frech und witzig. Extra 3 - die einzige Satiresendung.',
'23817212':'Das politische Satiremagazin im Ersten mit Studiogästen aus Politik, Kultur, Wirtschaft und Boulevard.',
'26111552':'',
'31938368':'In #EinMomentDerBleibt schildern Flüchtlinge zum ersten Mal überhaupt ihre bewegende Geschichte.',

#F
'249202':'',
'310854':'FAKT berichtet über Hintergründe und aktuelle News aus Politik und Wirtschaft. Videos zur Sendung finden Sie hier.',
'7545460':'Das Thema der Woche wird im MDR-Polittalk diskutiert - kontrovers, emotional, hintergründig. Die Sendung kommt im wöchentlichen Wechsel aus Magdeburg, Erfurt und Dresden.',
'13271346':'Geschichten rund um das turbulente Leben der sympathischen Patchwork-"Familie Dr. Kleist".',
'643290':'Ulrich Deppendorf und Thomas Baumann sorgen dafür, dass Politiker zu aktuellen Fragen "Farbe bekennen".',
'6223214':'',
'14912700':'Aktuelles und Faszinierendes aus der Welt der Wissenschaft, Forschung und Technik, moderiert von Gunnar Mergner.',
'27156308':'Die sogenannte "Königsdisziplin"',
'28777454':'Sechs Stadien, 24 Teams, ein Titel: Die Endrunde vom 6. Juni bis 5. Juli.',
'21675666':'Die FIFA Fußball Weltmeisterschaft 2014 in Brasilien. Alle Videos.',
'8758566':'Spielfilm',
'27258646':'Film & Serie in Einsfestival',
'17603924':'',
'25505674':'Filme im hr-fernsehen: Märchenfilme und anderes.',
'1933898':'Fernsehfilme des Ersten Deutschen Fernsehens als Video on Demand.',
'10009780':'Ein Wiedersehen mit bekannten Film-Klassikern, Spannung und Unterhaltung.',
'10318946':'Filme der Reihe "FilmMittwoch im Ersten" als Video',
'24787788':'',
'8638764':'Der "Flohmarkt" wandert gerne auf dem schmalen Grat zwischen Kunst und Kitsch. Ob Alpenpanorama, Bronzebüste oder gut erhaltene Küchenmaschinen aus Großmutters Zeiten - alles findet seinen Platz und seine Liebhaber.',
'14912642':'Rätselhafte Ereignisse, magische Gegenstände, ein geheimnisvoller Falke und eine Gruppe Schüler, die in ein Zeitloch geraten, sind die perfekten Zutaten für ein spannendes Nachmittagsprogramm...',
'209758':'Das Sport-Magazin "Flutlicht" zeigt aktuell und kompetent die Höhepunkte des Sport-Wochenendes mit dem Schwerpunkt Fußball-Bundesliga aus Rheinland-Pfalz. Immer sonntags ab 21:48 Uhr im  SWR Fernsehen.',
'16874426':'Eckart von Hirschhausen präsentiert die große Familienshow mit der Maus und vielen außergewöhnlichen Kinderfragen.',
'22673646':'Frankenschau',
'14913732':'Frankenschau aktuell',
'31081388':'Die Roadshow mit Sabine Heinrich',
'7535528':'frauTV: Das Frauenmagazin im WDR',
'19248874':'',
'13618400':'Sternekoch Björn Freitag gibt handfeste Tipps für den Verbraucher und nie gesehene Einblicke in die Lebensmittelindustrie.',
'17989562':'freizeit',
'7545196':'Autoren zu Gast bei Susanne Fröhlich',
'247338':'',
'12772246':'45 Min zeigt Filme über spannende Themen, die Menschen im Norden bewegen. Die Doku-Reihe findet überraschende Antworten auf Fragen, die sich im Alltag stellen.',

#G
'21034796':'Das Gartenmagazin mit Markus Phlippen',
'33031940':'Das TV-Magazin gibt auf innovative, informative und unterhaltsame Weise Einblicke in die komplexe Welt der Gärten und der Natur.',
'30025068':'"GEFÄLLT MIR! – Die total vernetzte Show" im WDR - moderiert von Matthias Opdenhövel - feiert das Beste aus der skurrilen Welt des Internets.',
'28362548':'In "Gefragt – Gejagt" tritt ein Team von vier Kandidaten gegen ein Superhirn, den "Jäger", an. Keine leichte Aufgabe, denn die Jäger sind ausgewiesene Quizprofis aus der deutschen Quiz-Nationalmannschaft.',
'9603072':'Reportage-Reihe auf Spurensuche an Orten weitgehend unbekannter Zeitgeschichte in Berlin und Brandenburg',
'25993150':'Große Orte mit Geheimnis',
'14912902':'Geist & Gehirn',
'14913400':'Geld und Leben',
'15713292':'In einem Dokudrama verkörpert Götz George seinen Vater, den Jahrhundertschauspieler Heinrich George.',
'14913378':'Franz Xaver Gernstl und sein Team, Kameramann Hans Peter Fischer und Tonmann Stefan Ravasz, muss man nicht mehr vorstellen – sie sind über die Grenzen Bayerns hinaus bekannt, für ihre feinen und eigenwilligen Reisereportagen.',
'29256952':'Die eigentlich spießige Maus Stilton lebt in Mausilia auf der Mäuse-Insel. Er arbeitet als Verleger der Tageszeitung "Neue Nager-Nachrichten". Am liebsten aber schreibt er Geschichten über seine aufregenden Abenteuer und löst Kriminalfälle.',
'11768582':'Geschichte Mitteldeutschlands geht auf lebendige Spurensuche in der Vergangenheit unserer Heimat - mit Geschichten, die spannend sind, unterhaltsam und emotional.',
'8412258':'Wir gehen auf lebendige Spurensuche in der Vergangenheit unserer Heimat - mit Geschichten, die spannend sind, unterhaltsam und emotional. So wie die Geschichte selbst.',
'3374172':'Geschichten aus Hessen, von Kassel bis Darmstadt, vom Land und aus der Großstadt im hr-fernsehen.',
'8758212':'Geschichte',
'17986474':'Gesundheit!',
'14912710':'Seit 2003 talkt Werner Schmidbauer mit prominenten Gästen hoch oben in den Bergen: "Gespräche in freier Natur werden viel authentischer, als wenn man die Leute im Studio interviewt", hat Schmidbauer festgestellt.',
'2467350':'Zoogeschichten aus Frankfurt und Kronberg.',
'18929644':'Was muss man tun, um einen scheuen Tiger vor die Kamera zu bekommen? Wie sorgt der Zoo dafür, dass unter den Tieren gute Nachbarschaft herrscht? Und warum sind bei den Seepferdchen die Väter für die Kinderaufzucht zuständig? Unsere Zoogeschichten erzählen es Ihnen.',
'20281138':'Was bieten und verbieten Islam, Christentum, Judentum und Hinduismus den jungen Gläubigen, wenn für sie die aufregende Suche nach der eigenen Sexualität beginnt?',
'7545428':'Was glaubst Du denn? Buddhist, Jude oder Christ – Glaubwürdig erzählt Geschichten von Menschen und ihrem Verhältnis zur Religion. Menschen, die für ihren Standpunkt eintreten, die schwierige Zeiten erlebt und dennoch ihr Gottvertrauen nicht verloren haben. Geschichten vom Leben und wie man es meistert.',
'14913086':'Armin Nassehi, Professor für Soziologie an der Ludwig-Maximilians-Universität München, wirft in 13 Folgen einen Blick auf unsere Gesellschaft - nicht mit soziologischen Fachbegriffen und komplizierten Ableitungen, sondern immer nah an dem, was Mitglieder moderner Gesellschaften täglich erleben.',
'2833732':'Reportagen zu Themen des religiösen und gesellschaftlichen Lebens.',
'14913096':'Deutsch ist eine wichtige Voraussetzung für einen erfolgreichen Schulabschluss. Deutsch zu lernen kann aber auch Spaß machen! Das beweisen dir Steffi Chita und ihre Schüler. Gemeinsam packen sie den Stoff der 9. Hauptschulklasse an und geben dir viele praktische Tipps.',
'14913106':'Englisch ist eine Weltsprache. Du brauchst sie im Urlaub, im Unterricht und immer mehr auch im Alltag. Wir helfen dir dabei, die englische Sprachwelt zu erschließen: Wie ging das mit den Zeiten? Wie steigert man Adjektive? Michael Meisenzahl erklärt\'s dir, ganz einfach!',
'14913850':'In Mathe verstehst du nur Bahnhof? Keine Sorge, Sebastian Wohlrab und seine Schüler helfen dir weiter. Begleite sie an viele spannende Orte, zum Beispiel in ein Fußballstadion, eine Schreinerei oder in eine Flugwerft. Du wirst staunen, wo du im Alltag überall auf Mathematik triffst.',
'3001570':'Auf der Suche nach kleinen und großen Fischen. Videos zur Kultserie: Verpasste Folgen für 7 Tage, Making of und Interviews.',
'14912750':'Günter Grünwalds bayerische Comedy-Show mit den Top-Kabarettisten Helmut Schleich und Willy Astor! Der lustigste Start ins Wochenende mit schonungslos deftigem Humor und prominenten Gästen aus ganz Deutschland.',
'249330':'',
'8109878':'Archiv: Der Polittalk aus dem Herzen der Hauptstadt: Günther Jauch diskutiert in seiner Sendung mit interessanten Gästen aus Politik und Gesellschaft das Thema der Woche.',

#H
'19811342':'In der neuen Comedy-Talkshow "Habe die Ehre" prüfen die Kabarettisten Wolfgang Krebs und Christine Eixenberger sowie BAYERN 3-Moderator Bernhard Fleischmann als Außenreporter nicht-bayerische Promis auf ihre Bayern-Tauglichkeit.',
'9537582':'Der Nachmittag im hr-fernsehen: Service im Plauderton, kombiniert mit etwas Klatsch und Tratsch. Bei einer Tasse Kaffee oder Tee plaudern wir mit interessanten Menschen aus Hessen, die etwas Besonderes können, tun oder haben.',
'25231206':'Wir sind stets nah dran an den niedersächsischen Themen und Menschen. Uns interessiert, was Sie aufregt und bewegt.',
'25231214':'Das Hamburg Journal ist das Stadtmagazin für die Hansestadt und informiert über das öffentliche Geschehen, politische Ereignisse und das kulturelle Leben der Stadt.',
'31893876':'Das Hamburg Journal ist das Stadtmagazin für die Hansestadt und berichtet in seiner Frühausgabe bereits um 18 Uhr in Kurzform das Neueste vom Tag.',
'17732560':'',
'17662568':'Regionale Comedy',
'14049128':'Hanseblick reist mit vielen Fragen bis an die Außengrenzen Europas. Sehnsuchts- und Fernweh-Fernsehen!',
'561146':'Das aktuelle Polit-Talkmagazin im Ersten - Videos zur Sendung finden Sie hier.',
'7545180':'MDR-Gesundheitsmagazin',
'3469854':'Immer donnerstags: Das Kulturmagazin im hr-fernsehen.',
'14913116':'Heimatbilder',
'3913636':'Geschichten über Land und Leute in Berlin und Brandenburg, erzählt von Carla Kniestedt und Ulli Zelle.',
'14913136':'Heimat und neue Perspektiven entdecken - das ist das Motto des Magazins "Heimatrauschen". Moderator Florian Wagner präsentiert Menschen, Geschichten und Orte in Bayern, die Tradition und modernen Stil auf besondere Art verbinden.',
'14913332':'Heimatsound',
'19264650':'Sport aus Hessen u.a. mit den Spielen der 3. Liga.',
'3473934':'Immer sonntags im hr-fernsehen: Woche für Woche ist herkules unterwegs zwischen Rhön und Upland, Weser und Vogelsberg.',
'30385176':'Begleiten Sie Moderator Dieter Voss auf seinen Reisen durch das herrliche Hessen. In jeder Ausgabe steht eine hessische Stadt oder Region im Mittelpunkt - mit ihren spannenden, ungewöhnlichen und unterhaltsamen Menschen und Geschichten und natürlich wunderschönen Aufnahmen! Wie der Name schon sagt - eben "Herrliches Hessen".',
'3343878':'',
'3469588':'Die Sendung im hr-fernsehen rund um traditionelle und moderne Gerichte und andere Leckereien.',
'18719278':'Aktuelles aus Hessen in den Extra-Sendungen des hr-fernsehens',
'3469022':'Immer sonntags im hr-fernsehen: Quizmaster Jörg Bombach begrüßt jeden Sonntag vier hessische Kandidaten aus vier verschiedenen Regionen. Die Fragekategorien: Hessische Politik, Wirtschaft, Klatsch und Leute, Geschichte und vor allem Mundart.',
'3366970':'Geschichten aus dem Leben im hr-fernsehen: Die Reporter sind in Hessen unterwegs, besuchen Menschen und erzählen deren Geschichten, begleiten sie im Alltag und bei besonderen Herausforderungen.',
'3301950':'Täglich um 19.30 Uhr im hr-fernsehen: Politik, Kultur, Wirtschaft und Unterhaltendes aus Hessen. Außerdem informiert hessenschau kompakt werktäglich um 16:45,17:50 und 22:30 Uhr',
'3473942':'Immer Freitags im hr-fernsehen: Veranstaltungs- und Ausflugstipps für Hessen.',
'13401106':'Wandern in den schönsten Regionen, zu Fuß, per Fahrrad, Ski oder Paddelboot. Katja Schmidt ist immer mit einem regionalen Auskenner auf Tour, aller zwei Wochen Sonntagnachmittags im MDR  FERNSEHEN.',
'14106094':'"Wir und unsere Nachbarn – damals und heute" ist das Grundmotto von "Heute im Osten". Die Sendung wird alle 14 Tage am Samstag um 18 Uhr und am Sonntag um 16:05 Uhr ausgestrahlt.',
'9951424':'Die Parlamentsdebatten aus dem Berliner Abgeordnetenhaus und dem Brandenburger Landtag.',
'13618324':'Die Sendung "HIER UND HEUTE" ist das regionale Reportagemagazin im WDR Fernsehen.',
'574758':'',
'3907830':'Magazin für Kirche und Religion im rbb Fernsehen',
'14923584':'Dr. Eckart von Hirschhausen nimmt die Zuschauer und Ratekandidaten mit auf eine faszinierende Reise in die Wunderwelt des Homo sapiens.',
'29503374':'Die Wissens- und Spielshow mit Dr. Eckart von Hirschhausen',
'3474872':'Immer samstags im hr-fernsehen: Das Magazin rund um Gesellschaft und Religion.',
'17624212':'Mit Scharfsinn und eigenwilligen Methoden ermitteln die beiden Polizeiobermeister Hubert (Christian Tramitz) und Staller (Helmfried von Lüttichau) im bayerischen Voralpenland und heizen dem Verbrechen ordentlich ein.',
'32325502':'Die Kult-Kommissare Hubert und Staller ermitteln in Oberbayern. Serie mit Helmfried von Lüttichau und Christian Tramitz.',
'30176536':'K.P. Huck ermittelt in Stuttgart, ist Ex-Bulle und hat eindeutig ein Problem mit Autorität.',
'27127872':'',
'31787402':'Volontärsfilme im MDR',
'7613208':'Hauswirtschaftsmeisterin Yvonne Willicks kämpft sich durch den Produkte-Dschungel im Haushaltsbereich.',
'27945360':'',
'15918032':'103.7 UnserDing - Das Jugendradio des Saarländischen Rundfunks zeigt regelmäßig coole Clips für junge Menschen.',

#I
'14913126':'Mehr als 300 Berufe im Dualen System, dazu kommen Lehrstellen bei Behörden und der Bahn. Doch welche Ausbildung ist für wen richtig? ARD-alpha bringt es auf den Punkt. "Ich mach\'s!" stellt jede Woche einen Beruf vor.',
'32588892':'Immer weniger Lehrlinge, immer weniger Facharbeiter: der deutschen Wirtschaft geht das Personal aus. Da wird Weiterbildung für Erwachsene immer wichtiger. "Ich mach\' weiter" zeigt, wie\'s geht.',
'22380516':'Prominente stellen sich bei Sandra Maischberger',
'5360144':'Dominik Graf hat mit seiner Krimiserie "Im Angesicht des Verbrechens" neue Maßstäbe gesetzt.',
'14913830':'"Im Schleudergang" rund um eine Schwabinger Wäscherei mit Gisela Schneeberger in der Hauptrolle tobt viel buntes Leben – eine Serie prall, komisch, hintersinnig und sehr bayerisch!',
'27081432':'',
'10535908':'in.puncto erklärt nicht wie\'s funktioniert, sondern wie es sich anfühlt. Moderatorin Nicole Köster probiert aus, worüber sie ihre Gäste löchert.',
'6032920':'Der ereignisreiche Alltag in der Sachsenklinik. Jetzt neu auch als Video für 7 Tage in der Mediathek!',
'13258516':'Die Geschichten rund um das Ärzteteam der Sachsenklinik fesseln jede Woche Millionen Fernsehzuschauer.',
'24966374':'Dr. Niklas Ahrend und sein Team im Johannes-Thal-Krankenhaus in Erfurt.',
'3411450':'Talk, Comedy und Musik: Die schönsten Momente der Late-Night-Show nach Müllerin Art finden Sie hier als Videos.',
'17025660':'',
'14049136':'Hochkarätiges Kabarett, Live-Musik und kuriose O-Töne: Alles das haben die Macher der Intensiv-Station im Gepäck, wenn sie auf Tour gehen.',
'1528132':'Interviews, Trailer und Hintergrundberichte zu Spielfilmen und Events rund um Das Erste.',
'33031936':'',
'13697880':'Top-Modebloggerin Jessica Weiß präsentiert 30 Minuten lang Fashion, Lifestyle und Trends ? alles was man wissen muss, um in der schönen, bunten Modewelt mitreden und mithalten zu können.',

#J
'33031928':'',
'22318404':'',
'14912496':'',
'14913420':'Jetzt red i – Europa, die bayerische Bürgersendung für Europa, diskutiert mit den Bürgern. Birgit Kappel und Tilmann Schöberl fragen nach: Was läuft schief in der EU? Wo muss sich dringend etwas ändern?',
'14913026':'Joseph von Fraunhofer',

#K
'247654':'',
'14913322':'Mit rasanten Stand-Up-Nummern, immer am Puls der Zeit, mit bissiger Ironie, schräg, intelligent, anspruchsvoll und mit jeder Menge Zwerchfell-Attacken - so präsentiert sich "Kabarett aus Franken".',
'243480':'',
'30559842':'Geschichtsstunde mal anders: Die Klappmaulpuppe Kater Karl alias René Marik streunt wieder durch unterschiedlichsten Epochen.',
'30159178':'Kann man Ob BMX, Kart fahren, Parcours oder Rollstuhlbasketball in nur 48 Stunden lernen? Johannes probiert es aus.',
'14913184':'"Habe Mut, dich deines eigenen Verstandes zu bedienen." Mit diesem berühmten Appell krönte Immanuel Kant seine Definition der Aufklärung. BR-alpha nähert sich dem schwierigen Werk des Meisterphilosophen auf einem außergewöhnlichen Weg: Anstatt über Kant zu reden, redet die Philosophiestudentin Sophie lieber mit dem schrulligen Professor aus Königsberg persönlich.',
'10187260':'Die MDR-Polit-Satire mit Lothar Bölck & Michael Frowin',
'9341378':'Hier finden Sie eine Auswahl der Sendungen im Ersten rund um Karneval und Fasching als Video.',
'7382518':'Er träumt von der großen Samstagabend-Show im rbb Fernsehen, doch die Intendantin schickt ihn immer wieder auf Expeditionen...',
'14913678':'kinokino - das Filmmagazin im Bayerischen Fernsehen. Die wichtigsten Kinoneustarts der Woche, alles über Filmemacher und Stars, Filmpreise und Filmfestivals. Jeden Mittwoch um 22.45 Uhr.',
'15447312':'Der andere Blick',
'4112710':'Kirchliche Sendungen im Ersten.',
'3913652':'politisches Magazin für Berlin und Brandenburg',
'14913194':'Wie kam die Schildkröte auf den Kopf des Aischylos? Von wem wurde schon früh in der Literatur der "Cliffhanger" erfunden? Und warum war der 16. Juni 1904 für James Joyce so wichtig? Antworten gibt Tilman Spengler in dieser Sendereihe.',
'10535916':'Das junge Talk- und Reportagemagazin für Pop, Politik und Gesellschaft - weil Du neben Party auch Hirn im Kopf hast!',
'13005518':'Das legendäre Koch-Duo aus dem Schwarzwald',
'16335704':'Max Moor begleitet bekannte Sterneköche, z. B. Kolja Kleeberg und Stefan Hartmann, – in die Küche und nach Brandenburg, wo sie auf die Suche nach lokalen Erzeugern gehen, die für die Spitzengastronomie aber auch für die heimische Küche produzieren.',
'12877154':'Der Talk im WDR',
'13005502':'Dieter Könnes im Einsatz für Verbraucherrechte',
'14913214':'Konrad Duden',
'431796':'Kontraste – das kritische Magazin aus Berlin. Keine Politikerphrasen, kein Infotainment: Kontraste geht den Dingen auf den Grund, neugierig und mit sorgfältiger Recherche',
'14913688':'Kontrovers',
'443428':'Tricks und Phänomene aus Natur, Wissenschaft und Technik.',
'16361776':'deutsch-polnisches Magazin im rbb Fernsehen und im polnischen TVP 3',
'27680744':'',
'14199392':'"Kripo live" mit Axel Bulthaupt - die Fernseh-Fahndungssendung, in der ungelöste Kriminalfälle vorgestellt sowie Tipps für Verbrechensprävention gegeben werden.',
'3487828':'Das Kulturjournal berichtet jede Woche über Neues aus der norddeutschen und internationalen Kulturszene und vom Büchermarkt - montags um 22.45 Uhr im NDR Fernsehen.',
'19396202':'',
'4040692':'Kulturspiegel - eine aktuelle Magazinsendung im regionalen Vorabendprogramm des SR Fernsehens.',
'18349524':'',
'14912882':'Kunst & Krempel',
'17603882':'Kurzfilme aller Genres werden freitags um 1:30 Uhr und zweimal im Jahr in der MDR Kurzfilmnacht gezeigt.',
'24833612':'Kurzfilm-Nacht',
'16272574':'Kompakte Informationen und Tipps zu Sport, Verbraucherfragen, Tiervermittlungen, Garten und Gesundheit - werktags um 16:50 Uhr',
'14912892':'Seit über 50 Jahren beweist der Komödienstadel mit klarem Bekenntnis zu Dialekt und Heimatthemen, dass Volkstheater im Fernsehen ein zeitloses Genre ist.',
'30292384':'Die Kanzlei',
'13489530':'Serie',
'11321236':'',
'14912720':'Die Komiker bringen das Lebensgefühl der Bayern auf den Punkt: Hinterfotzig, schräg, krachert - aber sehr liebenswert. Constanze Lindner, Eva Mähl, Florian Simbeck und Uli Bauer bürgen für schrägen bayerischen Humor.',
'28898340':'Im beschaulichen bergischen Städtchen Oberbreitbach sorgt  Belinda Mommsen als Tierheilpraktikerin für Wirbel.',
'23162708':'Dyslexie',

#L
'24073074':'Kabarettistischer Abend mit reiner Frauenbesetzung',
'23019652':'Kurt Landauer',
'11360794':'Der schnelle Überblick über die wichtigsten Ereignisse in Sachsen, Sachsen-Anhalt und Thüringen.',
'983328':'Reise',
'14464364':'Die Reportagen führen in unerforschte Gebiete, zeigen das Leben fremder Völker, stellen interessante Städte, aber auch Traumreiseziele vor.',
'207590':'',
'1026398':'',
'254078':'',
'205724':'',
'250286':'Landesschau BW',
'24925108':'',
'207880':'Landesschau RP',
'2790120':'LS unterwegs',
'14912808':'Mit "Landgasthäuser" erleben Zuschauer Gastlichkeit, Gaumenfreuden und Feiertage neu. Seine Reise führt Filmemacher Werner Teufl zu Landgasthäusern mit deftiger Hausmannskost und Gourmetküche.',
'14049144':'Moderatorin Heike Götz besucht Menschen aus der Region und ist immer auf der Suche nach den großen und kleinen Geheimnissen Norddeutschlands.',
'30180608':'Eine Landserie von Lola Randl',
'7470294':'Ein alter Bus, sechs sympathische Frauen vom Land und jede Menge leckere Rezepte.',
'14128644':'',
'10535924':'Noch ein Reportagemagazin? Nein, ?LEBEN!? fällt aus der Reihe: Menschen zwischen 16 und 30 erzählen ihre bewegende Geschichte selbst ? ohne Moderation oder Inszenierung. Das Magazin gibt ihnen Raum, über ihre Ideen, ihre Herausforderungen, Leidenschaften, Krisen und Erfolge zu sprechen.',
'23950672':'Hier können Sie interessante Persönlichkeiten aus dem Sendegebiet kennenlernen, die sich um Kunst, Kultur, Geschichte oder auf anderen Gebieten des Alltags verdient gemacht haben - Menschen von heute oder aus vergangenen Zeiten ...',
'14913740':'Lebenslinien',
'18941746':'Mit Sven Voss',
'7825656':'Lecker aufs Land',
'18965696':'Sendungen im hr-fernsehen rund um traditionelle und moderne Gerichte und andere Leckereien.',
'28638166':'',
'30117288':'Deutschlands beste Athleten treten vom 22. bis 30. August 2015 bei der Leichtathletik-WM in Peking an. Sportschau.de/peking berichtet per Livestream und Live-Ticker aus dem Nationalstadion.',
'1100796':'',
'14912624':'LeseZeichen',
'8758476':'',
'7545188':'Wissen für alle',
'25307758':'',
'13618392':'Mit dem Motorradgespann auf Schnitzeljagd durch NRW',
'14912680':'LIDO',
'33031912':'Ist das Ölgemälde, das schon lange auf dem Dachboden verstaubt, vielleicht von einem berühmten Maler? Oder das Schnäppchen vom Flohmarkt ein wahrer Kunstschatz?',
'5280':'Kultstatus im Ersten und in der Mediathek: Die vergangenen Folgen der Lindenstraße finden Sie hier als Video on Demand.',
'14913222':'Die BR-alpha-Reihe Lógos bereitet Themen und Tagungen der Katholischen Akademie in Bayern journalistisch auf.',
'25377998':'Informativ und unterhaltsam: Die Lokalzeit am Samstag',
'7293556':'Die Lokalzeit aus Aachen ist das regionale Magazin im WDR Fernsehen für den Bereich rund ums Dreiländereck D-NL-B.',
'7293564':'Die Lokalzeit aus Bonn ist das regionale Magazin im WDR Fernsehen für die Stadt Bonn und Umgebung.',
'7293572':'Die Lokalzeit aus Dortmund ist das regionale Magazin im WDR Fernsehen für\'s östliche Ruhrgebiet.',
'7293588':'Die Lokalzeit aus Duisburg ist das regionale Magazin im WDR Fernsehen für\'s westliche Ruhrgebiet und den Niederrhein.',
'7293580':'Die Lokalzeit aus Düsseldorf ist das regionale Magazin im WDR Fernsehen für den Großraum Düsseldorf.',
'7293596':'Die Lokalzeit aus Köln ist das regionale Magazin im WDR Fernsehen für den Großraum Köln.',
'7293604':'Die Lokalzeit Bergisches Land ist das regionale Magazin im WDR Fernsehen für Wuppertal und das bergische Land.',
'7293612':'Die Lokalzeit Münsterland ist das regionale Magazin im WDR Fernsehen für\'s Münsterland.',
'7293620':'Die Lokalzeit OWL ist das regionale Magazin im WDR Fernsehen für Ostwestfalen - Lippe.',
'7293628':'Die Lokalzeit Ruhr ist das regionale Magazin im WDR Fernsehen für\'s Ruhrgebiet.',
'7293636':'Die Lokalzeit Südwestfalen ist das regionale Magazin im WDR Fernsehen für\'s Siegerland und Südwestfalen.',
'15404624':'Die Sendung entführt den Zuschauer in die Städte und Regionen, die die Passagiere der MS Albatros aus "Verrückt nach Meer" besucht haben.',
'33031904':'Reporter und Reporterinnen verraten, was am Wochenende in Norddeutschland los ist und geben Tipps für schöne und interessante Ausflüge.',
'3914776':'Magazin in niedersorbischer Sprache mit deutschen Untertiteln für die sorbisch/wendische Bevölkerung',
'14912962':'Als aufgeklärte Menschen wissen wir, dass wir von unserer Kultur geprägt sind - doch greifen diese Einflüsse wesentlich tiefer und weiter als wir denken. In der Sendereihe "Der lange Schatten von Kultur" hinterfragt der Ethnologe Frank Heidemann das Eigene und öffnet den Blick für das Fremde.',
'11992544':'Die Reportage-Reihe begleitet Menschen aus Berlin und Brandenburg, die ihre Lebenssituation verändern wollen oder müssen.',

#M
'9980146':'Das MDR-Spiel',
'32943652':'Das MDR Azubi-Magazin',
'29815332':'Die Programmoffensive des WDR Fernsehen',
'22597030':'\'Made in Berlin - Gute Ideen und andere Katastrophen\' ist eine Reise in das neue Berlin voller kreativer Ideen und großer Risiken.',
'2499530':'',
'4040700':'Jeden Donnerstag:<br/>							Aktuelles und Hintergründiges aus dem Saarland.',
'14913310':'Maibockanstich 2015',
'3414220':'Maintower, das Boulevardmagazin des Hessischen Rundfunks, zeigt, was Hessen bewegt. Täglich um 18 Uhr mit den spannendsten Bildern und Geschichten des Tages, präsentiert von Susann Atwell und Petra Neftel.',
'1585104':'',
'311210':'Talk im Ersten mit Sandra Maischberger. Die Videos zu den vergangenen Sendungen finden Sie hier.',
'10318954':'Spannende Krimis aus Schweden',
'22654962':'MANN/FRAU',
'8917856':'Neuverfilmungen von Märchenklassikern im Ersten. Videos für 7 Tage in der Mediathek.',
'14049152':'Lebensraum für Mensch und Tier, Forschungsfeld für Wissenschaftler, Freizeitparadies und Grundlage für das Leben: Das Magazin der Meere zeigt die ganze Vielfalt.',
'13618388':'Konsumgüter auf dem Prüfstand',
'30913136':'Im Mittelpunkt der DDR-Fernsehserie stehen die Geschehnisse in einem märkischen Dorf zwischen 1939 und 1960. Es sind Geschichten von Hoffnung und Freundschaft, Liebe und Leid in wechselvollen und gefährlichen Zeiten.',
'7486252':'markt: Das Wirtschafts- und Verbrauchermagazin',
'14049160':'Markt berichtet über die aktuellen Themen zu Wirtschaft und Sozialfragen sowie Hintergrundinformationen zum Verständnis wirtschaftlicher Zusammenhänge.',
'1665616':'',
'14913232':'Mathematik ist spannend, Mathematik ist faszinierend, aber viele Menschen haben eine Hemmschwelle, sich mit der wahrscheinlich ältesten aller Wissenschaften zu beschäftigen. Diese Hemmschwellen abzubauen, ist das Ziel der Sendereihe "Mathematik zum Anfassen".',
'15123138':'Neben dem MDR FERNSEHEN gibt es viele Videos im MDR, die nur online zu sehen sind. Unter MDR + findet man spannende Videos  - exklusiv im Netz.',
'7545132':'Die wichtigsten Nachrichten und Sportmeldungen aus Sachsen, Sachsen-Anhalt und Thüringen.',
'7545100':'In komprimierter Fassung von anderthalb Minuten informieren wir Sie über die aktuellen Nachrichten des Tages.',
'7545436':'Wenn in Sachsen, Sachsen-Anhalt und Thüringen etwas wirklich Wichtiges und Dramatisches passiert, dann berichtet "MDR extra" kompetent, seriös und aktuell.',
'7545092':'Claudia Look-Hirnschal ist die Frau mit dem grünen Daumen. Neugezüchtete Pflanzen,  aktuelle Deko-Ideen, exklusive Gartentipps von Fachleuten und attraktive Ziele für Gartenfans - das alles präsentiert sie im MDR FERNSEHEN. Und auch für (fast) jedes Gartenproblem hat die Gartenredaktion eine Lösung.',
'7545148':'Aktuelle Bilder und Informationen aus Politik und Wirtschaft, aus Wissenschaft, Kultur und Sport aus Sachsen-Anhalt.',
'7545252':'Aktuelle Meldungen aus Sachsen-Anhalt kurz und knapp in 90 Sekunden.',
'7545204':'Aktuelle Bilder und Informationen aus Politik und Wirtschaft, aus Wissenschaft, Kultur und Sport aus dem Freistaat Sachsen.',
'7545292':'Aktuelle Meldungen aus Sachsen kurz und knapp in 90 Sekunden.',
'7545420':'Das aktuelle Fernsehen – Regionalmagazin aus Thüringen mit Informationen aus Politik und Wirtschaft, aus Wissenschaft, Kultur und Sport.',
'7545332':'Aktuelle Meldungen aus Thüringen kurz und knapp in 90 Sekunden.',
'18679606':'Das Ländermagazin',
'18560338':'Das MDR-Mittagsmagazin',
'18560348':'Die Moderatoren Peter Imhof, Katrin Huß und Anja Koebel melden sich im wöchentlichen Wechsel mit einem unterhaltsam-informativen Programm. Sie berichten über aktuelle Ereignisse, über Menschen aus der Region, sprechen mit Prominenten und geben praktische Tipps.',
'9375388':'Wenn in Sachsen, Thüringen oder Sachsen-Anhalt gefeiert wird, dann ist ein MDR vor Ort-Team dabei. Die Moderatorinnen entdecken das Besondere, erleben das Unerwartete und lernen Leute kennen, die das Ereignis zu dem machen, was es ist – neugierig, skurril und schräg. Die Emotionen des Tages immer samstags 16.05 und rund um die Uhr in der MDR-Mediathek.',
'30383700':'Geschichtsmagazin mit Mirko Drotschmann',
'27866224':'In der 6-teiligen Sendereihe werden Themen behandelt, die in der heutigen Medien- und Internetgesellschaft jeden etwas angehen. Immer zwei Sendungen beschäftigen sich aus unterschiedlichen Blickwinkeln mit einem großen Thema.',
'17603850':'Daily Doku 20x25 min. /2010. Sechs Jugendliche starten in das Abenteuer ihres Lebens und testen, wie sich das Leben in einer völlig fremden Familie auf Zeit anfühlt.',
'20413134':'Peter Escher auf den Spuren des Schicksals',
'33031896':'Information und Unterhaltung aus Norddeutschland, dazu interessante Talkgäste, spannende Live-Reportagen und köstliche Rezeptideen.',
'14049168':'Die Reihe widmet sich der Pflege der ländlichen Traditionen Norddeutschlands und dem Zusammenleben von Familien auf dem Land.',
'10107494':'',
'29323100':'WDR-Köche kochen gemeinsam nach ausgefeilen Rezepten',
'7535538':'Menschen hautnah: Lebensgeschichten, Schicksale, Abenteuer',
'8758536':'',
'8758102':'',
'6223222':'Mensch Leute',
'3475172':'Mittwochs um 20.15 Uhr: Das Marktmagazin im hr-fernsehen, mit zahlreichen Tipps für Verbraucher.',
'27040332':'900 Schafe und Ziegen, Schäfer Maik Randolph und die Prominenten - mit ihnen geht es einmal quer durchs Land.',
'17624222':'365 Tage lang kein anderes Ziel als – die Welt. Zwei junge Männer begeben sich nur mit dem Nötigsten, einem Laptop und einer Kamera auf eine offene Reise. Jede Woche zeigen sie uns ein Video von ihren Erlebnissen unterwegs.',
'314636':'Aktuelle News und Berichte aus dem In- und Ausland. Die Videos und den Livestream zur Sendung finden Sie hier.',
'12877190':'Kabarett: Spitzes zur Nacht',
'30495354':'',
'438224':'Unbequem sein, irritieren, provozieren - Monitor will Hintergrund liefern, Diskussionen anstoßen, Themen setzen.',
'26727218':'MORA zeigt Menschen in Echtzeit bei der Arbeit. 60 Minuten lang, ohne Schnitt, Kommentar und Musikuntermalung. Zuschauer können dabei sowohl ihr Zeitempfinden als auch die eigene Sehgewohnheit hinterfragen, bei Bedarf entspannen - und "entschleunigen".',
'6683938':'Kommissar Mehmet Özakin ermittelt in Istanbul',
'25679266':'Sophie Haas ermittelt',
'435054':'Jeden Morgen Neuigkeiten vom Tage und jede Menge Service (in den ARD-Wochen). Das ARD-Morgenmagazin wird im wöchentlichen Wechsel mit dem ZDF gesendet.',
'11501420':'Die Tigerenten-Reporter zeigen\'s euch.',
'14913468':'Die Münchner Runde ist die politische Talksendung im Bayerischen Fernsehen. Im Wechsel diskutieren Ursula Heller und Sigmund Gottlieb mit Verantwortlichen, Experten und Betroffenen aus Politik, Wirtschaft und Gesellschaft.',
'18967316':'Musiksendungen im hr-fernsehen: Schlager, Volksmusik, Chorfeste etc.',
'17603842':'',
'17603858':'Mit Uta Bresan',
'14913242':'Ein unterhaltsamer Leitfaden durch die (europäische) Musikgeschichte wird präsentiert vom Musiker Bob Ross, der Mitglied der "Münchner Philharmoniker" ist und Chef der Bläsergruppe "Blechschaden".',
'7021916':'Von Pop bis Klassik: Musiksendungen im Ersten',
'23445080':'Neue Doku-Reihe über Menschen, die gegen Unrecht kämpfen',
'15304566':'Direkt, persönlich und individuell ? in ?My Hometown? nehmen die angesagtesten deutschen Musiker die Zuschauer mit auf eine ganz persönliche Tour durch Ihre Heimatstadt. Die Künstler zeigen Orte von persönlicher Bedeutung, geben Insider-Tipps, erzählen aus ihrem Leben in ihrer Hometown.',
'14913252':'Mythen',
'22876986':'Der Markencheck',
'22380500':'Lach- und Sachgeschichten mit der Maus und ihren Freunden',
'1458':'Die Sendung mit der Maus ... und dem Elefanten. Hier gibt es die vergangenen Sachgeschichten aus einem Maus-Jahr als Video.',
'22834010':'Mit dem Montags-Check im Ersten wollen wir dem gestiegenen Bedürfnis unserer Zuschauer nach Orientierung in einer immer unübersichtlicheren Alltagswelt Rechnung tragen.',
'20985044':'',
'25983654':'Im Mutcamp in Südafrika stellen sich 6 Jugendliche ihren Ängsten. Es ist eine Reise die ihr Leben verändern soll.',
'7825658':'Richling',

#N
'14912614':'',
'247716':'Der SWR Talk-Klassiker: Das Nachtcafé ist keine Arena für Exhibitionisten und Voyeuristen. Zynismus und Krokodilstränen haben keinen Platz, wohl aber Menschen aller Art, die den Zuschauern etwas zu erzählen haben.',
'31522472':'Die NachtKultur/NachtMusik, immer Donnerstagabend gegen 23:30 Uhr, ist DER Platz für Musik und Kultur im rbb Fernsehen.',
'14913146':'Nachtlinie',
'331152':'Die wichtigsten Ereignisse des Tages in der Zusammenfassung.',
'11573640':'Nadia Kailouli ist unterwegs im Auftrag der Liebe...',
'7545244':'Was im Leben wichtig ist ... Mehr Freizeit oder lieber mehr Geld? Kann Liebe Sünde sein? Wann ist der beste Zeitpunkt für ein Kind? Nah_dran will wissen, was dem Leben Sinn gibt, und lässt Menschen von ihren Krisen, Träumen und Hoffnungen erzählen.',
'3849826':'Videos zu den Tiergeschichten aus dem Zoo Hellabrunn',
'17603854':'',
'1026394':'',
'14049240':'Die Sendung über typische norddeutsche Landschaften, einheimische Tiere und Pflanzen. Reportagen über bekannte und unbekannte Naturparadiese.',
'14464388':'Von Montag bis Freitag, täglich am Nachmittag und am Abend: aktuelle Nachrichten und Informationen aus dem ganzen Norden aus der Redaktion NDR aktuell.',
'14049248':'N-JOY, das NDR Fernsehen und MySpace suchen das Comedy Talent Norddeutschlands.',
'14049264':'Videos aus dem regionalen Programm des Norddeutschen Rundfunks in Hörfunk und Fernsehen.',
'3750154':'',
'16409712':'Mal amüsant, mal streithaft, mal nachdenklich. Immer lebendig und im besten Sinne des Wortes interessant. Ein Klassiker im NDR Fernsehen.',
'33031888':'Ein Wiedersehen mit interessanten und spannenden Gästen aus früheren Sendungen der NDR Talk Show, Erinnerungen an besonders aufschlussreiche, witzige, liebenswürdige und offene Gespräche.',
'14464356':'Büttenwarder liegt irgendwo zwischen Flensburg und Hamburg. Hier leben Kurt Brakelmann und Adsche Tönnsen, zwei Bauern mit Antworten auf alle Fragen des Lebens.',
'431486':'"neuneinhalb - Deine Reporter", erklärt jeden Samstag um 8:25 Uhr im Ersten gesellschaftspolitische Themen so, dass sie jeder versteht.',
'31893884':'Aus der Region für die Region: Von der harten Politik bis hin zu unterhaltsamen Heimatgeschichten - wir sind stets nah dran an den Menschen und ihren Themen.',
'3321800':'Bildung',
'3341592':'Comedy aus dem Waschsalon',
'21076392':'Luke Mockridge präsentiert die Comedy-Party aus dem Waschsalon. Lässig, lustig, Luke. We laugh! NightWash jetzt rewashed mit neuem Moderator und den besten Jung-Comedians Deutschlands.',
'25231222':'30 Minuten regionale Information und Unterhaltung aus dem Land - für das Land.',
'31893892':'In einer 15-minütigen Ausgabe zeigt das NDR Fernsehen ein regionales Magazin über wichtige Themen in Mecklenburg-Vorpommern - live und vor Ort.',
'14464404':'Einmal im Monat präsentiert das Team des Nordsee-Reports Reportagen und Hintergrundberichte von der Nordseeküste. Jede Sendung widmet sich einem Thema in seinen unterschiedlichen Facetten.',
'33031880':'Ausflüge und Reisen, Spaß und Sport, Menschen und Geschichten: Das Reisemagazin bietet viele Tipps und Serviceangebote für den ganzen Norden.',
'30596148':'Stand up, Poetry Slam, Musik-Comedy, witziger Diashow, Video-Tagebuch, Parodie  und und und...',
'1858312':'Politisches Kabarett als Video: Skandale, der Irrwitz des Alltags - Dieter Nuhr lässt sich nichts entgehen, was er humorvoll sezieren kann.',
'12882028':'Das Quiz im WDR',
'14049232':'Die 30minütige Reportage im Vorabendprogramm: über ungewöhnliche Menschen und ungewöhnliche Orte in Norddeutschland.',
'26460574':'Wunderbare Landschaften, faszinierende Tierwelten und spannende Menschen: die nordstory erzählt Geschichten aus dem Norden.',



#O
'246888':'',
'33031868':'"Offen gesagt" heißt die christliche Gesprächsreihe im NDR Fernsehen, die gemeinsam von der evangelischen und der katholischen Kirche konzipiert wurde.',
'19337182':'Die Schubert-Liveshow',
'14049176':'Die Ostsee, ihre angrenzenden Länder und deren Bewohner sind Themen des Ostseereports.',
'7545260':'Mit dem Rucksack der Sonne entgegen',
'3914784':'OZON unterwegs informiert unterhaltsam und spannend über neue Erkenntnisse aus Natur- und Geisteswissenschaften, Umwelt und Technik.',
'9397858':'"Der Osten – Entdecke wo Du lebst"  stellt geheimnisvolle Orte vor und erzählt ungewöhnliche Geschichten vom Leben in Mitteldeutschland.<br/>Axel Bulthaupt nimmt die Zuschauer mit auf Entdeckungsreise durch ihre Heimat.',

#P
'33436616':'Im Quiz von Jörg Pilawa laden Anne Gesthuysen und Frank Plasberg zum Duell. Das Ehepaar trifft auf ein anderes prominentes oder nicht-prominentes Paar. Wer setzt sich durch?',
'30403748':'',
'10027190':'Das rbb Fernsehen hat Zootiere und ihre Pfleger zu Fernsehstars gemacht!',
'310918':'Panorama ist eines der erfolgreichsten Politik-Magazine im Deutschen Fernsehen. Alle drei Wochen berichten wir pointiert, engagiert, aber nicht berechenbar.',
'14049184':'Das Politik-Magazin mit Susanne Stichler geht Missständen nach und dokumentiert die Folgen - hintergründig, engagiert und pointiert.',
'14049192':'Reporter des Politmagazins "Panorama" lösen schwierige Rechercheaufgaben und decken Missstände auf. Sie ermitteln verdeckt und konfrontieren Verantwortliche.',
'28704902':'Zoogeschichten',
'27228764':'Die Reporterinnen Paula und Anna waren schon in  Europa, Afrika, Australien und Amerika unterwegs um die verschiedensten Tiere zu treffen. Mit ihren wilden Liedern haben sie ihre Erlebnisse in Liedern festgehalten und erzählen in jedem Song von einem Tier.',
'8758252':'',
'12994052':'Die clevere Fernsehsendung - von Natur bis Kultur',
'25233996':'Die clevere Fernsehsendung - von Natur bis Kultur',
'33031854':'',
'432744':'Das Wirtschaftsmagazin als Video: "Plusminus" klärt auf, warnt und gibt Tipps rund um Wirtschaft, Recht und Finanzen.',
'14049200':'Kochen lernen mit Cornelia Poletto: Die Sterneköchin möchte in ihrer Sendung zeigen, wie einfach und lecker die italienische Küche ist.',
'1933890':'Krimi verpasst? Das aktuelle Video zur Krimireihe \'Polizeiruf 110\': Für 7 Tage nach Ausstrahlung als Video on Demand.',
'15757552':'',
'20960082':'Nachrichten wie sie sein sollten: packend, verblüffend, kritisch - und komplett frei erfunden. Präsentiert von Anne Rothäuser und Thieß Neubert.',
'311790':'Streitgespräch mit Journalisten moderiert von Sonia Seymour Mikich, Jörg Schönenborn oder Volker Herres.',
'23384174':'',
'739072':'Ausgewählte Trailer und Vorschauen auf Highlights im Ersten und mehr.',
'23961358':'punkt.',
'14912740':'puzzle',
'5556544':'Spannende Detektiv-Geschichten für Kinder',
'14913076':'Harald Lesch erklärt in acht Folgen die Physik Albert Einsteins – vom Photoeffekt über Schwarze Löcher, Gravitationslinien bis hin zur Bedeutung, die Einsteins Erkenntnisse für unser heutiges Leben haben.',

#Q
'7450356':'Das Wissenschaftsmagazin mit Ranga Yogeshwar',
'29592074':'Ralph Caspers nimmt den Zuschauer mit auf eine spannende Entdeckungsreise und hilft ihm die Geheimnisse der Welt zu enträtseln.',
'15037798':'Querbeet',
'10984584':'Büchermagazin für Kinder mit Marc Langebeck',
'14912730':'quer',
'14478074':'Das schnelle Quiz',

#R
'31931644':'',
'3907840':'Immer gut informiert mit dem Nachrichtenmagazin des rbb Fernsehens',
'8256334':'Live vor Ort, Sondersendungen oder Reportagen',
'3913628':'rbb-Magazin für Gartenfreunde in Berlin und Brandenburg',
'6331656':'rbb PRAXIS ist das multimediale Gesundheitsformat des Rundfunks Berlin-Brandenburg. Aktuell, praktisch, frisch und serviceorientiert, bietet die Fernsehsendung jeden Mittwoch um 20:15 Uhr live Informationen rund um Medizin, Gesundheit und Wohlbefinden aus der Region. Das Format umfasst zudem tägliche Beiträge um 14:05 Uhr im Inforadio sowie ein ausführliches Online-Angebot.',
'4112492':'Mit rbb SPEZIAL reagiert das rbb Fernsehen auf besondere Ereignisse in der Region Berlin/Brandenburg.',
'9597422':'spannende Sport-Ereignisse und herausragende athletische Leistungen aus Berlin und Brandenburg',
'30445748':'Regionales Nachmittagsmagazin für Berlin und Brandenburg. Information und Unterhaltung von Montag bis Freitag - jeden Tag live von einem anderen Ort.',
'9597140':'News vom Tag aus Berlin und Brandenburg, Tipps für den Abend in Mark und Metropole und Streiflichter aus den Nachbarländern',
'33216668':'Rebell Comedy',
'18910908':'Reisedokumentationen im hr-fernsehen.',
'10535948':'"Reload" geht den aktuellen Spiele-Trends auf den Grund und beleuchtet ihre Ursprünge. Dabei werden die Entwicklungen des Gamings von der Frühzeit bis heute analysiert.',
'27583606':'Rudi Rüssel erlebt mit seiner Familie viele tierische Abenteuer.',
'31522460':'',
'799280':'Hier sehen Sie ausgewählte Dokumentarfilme und Reportagen, unter anderem aus folgenden Reihen: Exclusiv im Ersten, Die Story im Ersten, Reportage im Ersten, Geschichte im Ersten ...',
'310120':'Als eines der besten investigativ arbeitenden Magazine deckt REPORT MAINZ regelmäßig bundesweit Missstände in Politik, Wirtschaft und Gesellschaft auf.',
'431936':'Investigativer Journalismus, seriöse Informationen und klare Positionen. Die Videos zu "report München" finden Sie hier.',
'5651338':'',
'8378414':'Die MDR-Talkshow',
'8051040':'Rockpalast, das Kult-Programm mit festem wöchentlichen Sendeplatz und regelmäßigen zusätzlichen Rocknächten.',
'317766':'Die verpassten Folgen der Telenovela finden Sie für 7 Tage als Video hier - zudem Interviews und Hintergrund-Berichte.',
'15178448':'Einfach königlich: Beiträge über Europas Königshäuser und Porträts über herausragende Persönlichkeiten',
'14049208':'Die Sendung präsentiert Geschichten mitten aus dem Hamburger Leben - komische, spannende, nachdenkliche und schräge.',
'33031850':'',
'3856484':'Die Reportage ist nah dran an den Menschen im Norden, ihrem Alltag, mit allen Träumen und Wünschen, aber auch Sorgen und Nöten. Diese Sendereihe beobachtet und hört zu und lässt den Zuschauer die Geschichte miterleben.',

#S
'4040708':'"Das grenzenlose Magazin" mit der Großregion Saar-Lor-Lux-Wallonien-Westpfalz beschäftigt: "SaarLorLüx - Geschichten von nebenan".',
'8638706':'Im "saartalk." erwartet die Gäste mehr als nur eine gemütliche Plauderrunde: kontrovers, kompakt und kurzweilig soll es sein. Schließlich gilt es, die Promis aus Politik und Gesellschaft in einer halben Stunde Sendezeit auf den Punkt zu befragen.',
'3846992':'',
'19429720':'Axel Bulthaupt begibt sich in seiner neuen Sendereihe "Sagenhaft" auf spannende Reisen durch Mitteldeutschland.',
'6503982':'Jeden Abend kommt das Sandmännchen mit einem Abendgruß und seinem Traumsand, um allen Kindern schöne Träume zu bescheren.',
'33031842':'(Rezepte zur Sendung auf NDR Text Seite 590 und im Internet www.ndr.de/kochen)',
'1512718':'',
'14913458':'Diese beiden sind ein Garant für hochkarätiges Kabarett: Michael Altinger und Christian Springer. Aus dem Münchner Schlachthof liefern sie 45 Minuten rasante Live-Satire - aktuell, bayerisch, politisch und immer ganz nah dran.',
'14912770':'Das ist Kabarett, Parodie und Unfug von und mit Helmut Schleich. Aktuell, schräg, urkomisch - und nur echt mit den posthumen Schimpftiraden des Franz Josef Strauß!',
'31893900':'Neben den neuesten Nachrichten und dem aktuellen Wetter ist das Thema des Tages Schwerpunkt der Sendung.',
'25231230':'Ob Politik oder Wirtschaft, Umwelt oder Kultur, jeden Abend von 19.30 bis 20.00 Uhr erfahren Sie, was sich am Tage in der Region zwischen Nord- und Ostsee ereignet hat.',
'9026246':'Hessische Spitzenpolitiker im hr-fernsehen im Gespräch: Moderator Thomas Kreutzmann begrüßt in Wiesbaden hessische Politiker aus Landtag oder Bundestag.',
'19100638':'',
'8757918':'Comedy',
'14912852':'Schuhbecks',
'14913702':'Schwaben & Altbayern',
'13455192':'Dokumentation',
'30129338':'Muss die Geschichte des Mauerfalls neu geschrieben werden? Eine mögliche und nicht ganz ernst gemeinte Antwort auf diese Frage gibt die neue sechsteilige Serie "Sedwitz".',
'7668808':'Zoogeschichten',
'13271334':'Magazin für Hörgeschädigte',
'14912912':'Sehen statt Hören',
'7545356':'Sendereihe in drei 3 Formaten: "SonntagsFragen" "Magazin" und "Reportage". Alle 3 Formate porträtieren Menschen mit Handicap, zeigen deren Stärke und beschäftigen sich mit Inklusion.',
'4172488':'Das Saarland einst und jetzt. Geschichte und Geschichten in alten Filmen und Erinnerungen von "Dabeigewesenen".',
'3362814':'Immer donnerstags: Das Gesundheitsmagazin am Vorabend im hr-fernsehen. Hintergrundwissen und Expertengespräche.',
'3373068':'Immer dienstags im hr-fernsehen: Wir informieren über Reiseziele rund um die Welt und geben Tipps für den Urlaub. Hintergrundwissen und Expertengespräche.',
'3380080':'Immer mittwochs im hr-fernsehen: Das Clever-TV live aus dem Maintower. Verbraucherinformationen rund um Produkte, Tarife und Dienstleistungen. Hintergrundwissen und Expertengespräche.',
'8131388':'Immer montags im hr-fernsehen: Die Ratgeber-Sendung zu den Themen Haus, Wohnen und Garten.',
'7582764':'Verbrauchertipps für jeden Tag',
'14464396':'Sich einen ganzen Tag lang mit der Kamera spontan und ohne Vorwarnung begleiten zu lassen - zu diesem Experiment versuchen NDR Moderatoren Menschen in Norddeutschland zu überreden.',
'30403570':'',
'29428368':'Das regionale Nachmittagsmagazin im rbb Fernsehen. Unterwegs in Berlin und Brandenburg den Sommer genießen und Menschen kennenlernen.',
'3434320':'Jenseits der Hektik des journalistischen Alltags gibt es im hr Fernsehen jeden Sonntag Zeit für ein spannendes Hintergrundgespräch. Persönlichkeiten aus Kultur, Wissenschaft, Wirtschaft, Politik und Religion schildern, wie sie die großen Fragen und Themen der Zeit sehen.',
'30743596':'Deutschlands erfolgreichstes Ermittler-Duo, Jan Josef Liefers und Axel Prahl, beide auch Musiker, Ossi und Wessi, machen sich in diesem Dokutainment-Format auf die Spuren der musikalischen Wiedervereinigung.',
'29951874':'Von hochwertigen Looks inspiriert – zum kleinen Preis nachgebaut',
'7873742':'',
'7784754':'Gastgeber Christoph Sieber empfängt Comedians und Kabarettisten.',
'14912578':'Spezlwirtschaft',
'10159874':'Sport',
'1135264':'"Sport am Samstag" ist Sport-Plattform für die 3.Fußball-Liga und viele weitere Sportarten im SWR-Sendegebiet von Rheinland-Pfalz und Baden-Württemberg. Die Sport-Stunde im SWR Fernsehen am Samstag ab 17 Uhr.',
'4040716':'Die regionale Sportschau - Ein Querschnitt durch das saarländische Sportgeschehen: jeden Sonntag von 18.45 Uhr bis 19.15 Uhr.',
'12772238':'Der Sportclub zeigt den Sport im Norden - aktuell, hintergründig, nah dran.',
'3647642':'',
'249964':'"Sport im Dritten" zeigt aktuell und kompetent die Höhepunkte des Sport-Wochenendes mit dem Schwerpunkt Fußball-Bundesliga aus Baden-Württemberg. Das Sport-Magazin im SWR Fernsehen BW am Sonntag ab 22.45 Uhr. Und ab dem 31. Mai 2009 wieder ab 21.45 Uhr.',
'7545380':'Aktueller Sport vom Tage',
'10160094':'Die Sportsendung im WDR-Fernsehen.',
'14913156':'Sport in der Abendschau',
'1493328':'Die Sendung erklärt, durchleuchtet und deckt auf - jeden Montag abend um 22.45 Uhr im WDR Fernsehen.',
'780932':'Ob CHIO, World Team Cup oder Rund um Köln: "Sport live im Westen" berichtet live von den Sportereignissen des Westens.',
'13470354':'Videos und Clips - Interviews und Extras rund um die Sportschau',
'53524':'Videos zur "Sportschau" - die Sportsendung des Ersten.',
'13470370':'Sportschau-Club',
'723230':'Videos zu "Sportschau live" - die Sport Events des Ersten Deutschen Fernsehens.',
'21318358':'Bettina Rust radelt durch Berlin und trifft Prominente und bisher weniger bekannte Kreative.',
'6329660':'',
'18794102':'',
'14912594':'Stadtspaziergänge',
'13655860':'Sie leben in Deutschland und haben einen so genannten ?Migrationshintergrund?. Sie sind Wanderer zwischen den Welten und den Kulturen, sie nehmen alles aufs Korn, was den traditionsbewussten Deutschen heilig ist ? und sich selbst gleich mit.',
'14913478':'stationen. Was die Welt zusammenhält. Mittwochs um 19 Uhr im Bayerischen Fernsehen. Ob als Magazin oder Dokumentation: Der thematische Bogen in "stationen." wird weit gespannt. Hier spiegelt sich wider, dass es in den Kirchen und zwischen den Religionen lebendig, kontrovers, bewegt und sogar widersprüchlich zugehen darf.',
'17603908':'',
'3914800':'Kulturmagazin des rbb Fernsehen: Neues aus Literatur, Kino, Theater, Oper und Kunst aus Berlin und Brandenburg',
'14913262':'Der Mensch will Kunst schaffen. Das beweisen Höhlenmalereien und bis zu 30.000 Jahre alte Figurenfunde. Bis heute haben sich bildende Kunst und Architektur ständig entwickelt. Reisen Sie mit uns durch die Geschichte der Kunst.',
'21060350':'Stofferl Well zeigt Bayern auf seine ganz spezielle Art. Unterwegs mit seinem alten Motorrad und so vielen Instrumenten, wie in den Beiwagen passen, macht er das, was er am liebsten tut: Er strawanzt durch Bayern, immer auf der Suche nach spannenden Menschen und Geschichten.',
'14847148':'Roberto Cappelluti prüft in strassen stars die Menschenkenntnis der Zuschauer und die seines prominenten Rateteams: Cappelluti hat drei Passanten auf der Straße ausgefragt. Ein dreiköpfiges Rateteam soll das Wissen und die Eigenarten der interviewten Straßenstars richtig einschätzen.',
'12882108':'Jupps Künstlerkneipe im Pott',
'5290':'Liebe, Leid und Intrigen im \'Fürstenhof\'. Die Folgen der letzten 7 Tage als Video und mehr zur Telenovela finden Sie hier in der Mediathek.',
'5286834':'',
'7313034':'',
'8758550':'',
'19673410':'',
'22380564':'Lach- und Sachgeschichten für Fernsehanfänger',
'22380500':'Lach- und Sachgeschichten mit der Maus und ihren Freunden',
'1458':'Die Sendung mit der Maus ... und dem Elefanten. Hier gibt es die vergangenen Sachgeschichten aus einem Maus-Jahr als Video.',
'8739802':'"Die Spur der Täter" ist mit der Kriminalpolizei Kapitalverbrechern auf den Fersen. Dabei geht es um die detailgetreue Rekonstruktion der Aufklärung von Morden und Überfällen.',
'7486242':'Die Sendereihe mit Dokumentationen aus dem In- und Ausland',
'14049104':'Für uns von "7 Tage..." ist das Leben eine Herausforderung und ein Abenteuer. Wir beobachten und begleiten diese Menschen, nehmen teil, leben in ihrem Leben.',

#T
'7543394':'Wo andere wegschauen, da schauen wir hin',
'4326':'Die Nachrichtensendung im Ersten.',
'6753968':'Immer aktuelle Nachrichten, viertelstündlich aktualisiert.',
'6737788':'Die Nachrichtensendung im Ersten.',
'12722002':'Die Nachrichtensendung im Ersten mit Gebärdensprache.',
'3914':'Aktuelle Themen ausführlich und hintergründig betrachtet.',
'5250638':'Kriminalreport des rbb Fernsehens',
'602916':'Krimi-Kult als Video: Die Tatort-Kommissare des Ersten sind dem Verbrechen auf der Spur. Zum Teil sind die Videos erst ab 20 Uhr abrufbar (freigegeben ab 12 Jahren).',
'15757542':'',
'30556746':'Die Kult-Krimireihe',
'29382356':'',
'3822098':'Ein Moderator, ein Gast und 30 Minuten Gespräch.',
'14046988':'politische Gesprächssendung des rbb mit Jörg Thadeusz und vier Kolleginnen und Kollegen aus dem journalistischen Fach',
'3914808':'Geschichte(n) aus der Mark: brandenburgisches kultur- und kunsthistorisches Magazin im rbb Fernsehen',
'8739794':'Seit 1991 ist der Filmemacher Thomas Junker für den MDR weltweit unterwegs. Im Mittelpunkt der Reisen in über 100 Länder stehen die Menschen, die er auf seinen Wegen getroffen hat.',
'16811160':'Die Serie rund um die beliebte Tierärztin Susanne Mertens und ihre Schützlinge im Leipziger Zoo.',
'3632902':'Gretas Leben in der Tierarztfamilie aus dem Schwarzwald.',
'12226390':'In der Sendung stellen nordrhein-westfälische Tierschutzvereine ausgesetzte oder in Tierheimen abgegebene Tiere vor, um sie an tierliebe Zuschauer zu vermitteln. Aber auch Themen rund um den Tierschutz und die Tierhaltung finden ihren Platz.',
'30214754':'',
'7705066':'Lustige Zoogeschichten aus Deutschland',
'7545228':'Das Tiermagazin des MDR',
'10432182':'vierteljährliche Sondersendung mit Tiervermittlung',
'8967946':'In der Tigerentenclub Spielshow mit Muschda und Lukas wetteifern zwei Schulklassen um den Sieg.',
'3407060':'Treffpunkt BW',
'431902':'Das Kulturmagazin im Ersten',
'14049256':'Die 30-minütige Reportage über norddeutsche Originale im Vorabendprogramm.',
'28405866':'"Naa, was willst du mal werden?" - Solche Fragen können ganz schön nerven! Um so besser, wenn man einfach mal in einen echt spannenden Job reinschnuppern kann - und zwar so richtig. Wo das geht? Na, bei "Dein Traumjob"!',
'24932130':'Tatortreiniger Schotty hat ein sehr pragmatisches Verhältnis zum Tod. Er trifft bei seiner Arbeit jedoch immer wieder Freunde und Angehörige der Verblichenen, welche ihm ins Bewusstsein rufen, dass an so einem Menschen vielleicht doch mehr dran ist, als das, was man hinterher wegschrubben muss.',

#U
'1555306':'Die Nonne und der Bürgermeister ... Neue Folgen der beliebten Serie für 7 Tage als Video!',
'7545140':'MDR-Magazin',
'15254962':'Mehr als drei Millionen Mal ziehen Menschen in Deutschland pro Jahr um, jeder von uns im Schnitt vier Mal im Leben. Ob neuer Job, neue Liebe, der Ausstieg aus dem alten Leben – es gibt viele Gründe. Aber immer ist ein Umzug ein Umbruch.',
'30858426':'Zweite Chance für ungeliebte Speisen',
'7545284':'unicato. Junger Film im MDR“ präsentiert jeden Monat Filme von Studierenden und Alumni. Moderiert wird das Magazin von Markus Kavka. Als Besonderheit erhält darin einer der jungen Filmemacher Gelegenheit, im Studio-Gespräch Idee, Genesis und Hintergründe seines Films zu erläutern. Online gibt es neben der Komplettsendung die Einzelfilme, Making-ofs, Bilder und Filmemacherporträts sowie weiteres Bonusmaterial.',
'14913036':'Modern, frisch und widerborstig berichtet UNKRAUT über neueste Entwicklungen im Umwelt- und Naturschutz, aber auch über Umweltsünden. Dazu ökologische Hintergründe - in Themensendungen vernetzt präsentiert.',
'33101394':'Die MDR-Sendereihe für’s Landleben. Ein Wochenende lang fangen Reporter, Kamera und Ton Lebensgefühl, Alltag und Höhepunkte, das Miteinander und die Zankereien, das Tun und Lassen, Freuden und Sorgen, skurrile und emotionale Momente von Dorfbewohnern in Mitteldeutschland ein.',
'13992080':'In den typischen, speziellen und einzigartigen Gerichten spiegeln sich Tradition, Vorlieben und Charakter der Menschen, zu deren Alltag sie gehören.',
'23783172':'',
'33404008':'Für die einen ist sie die schönste Nebensache der Welt, für andere überflüssiger Luxus. Und doch kommt keiner an ihr vorbei: der Mode.',
'14912650':'Unser Land',
'11094342':'Gute-Nacht-Geschichten mit Pittiplatsch, Plumps, Fuchs und Elster, Piggeldy und Frederick.',
'8405046':'Geschichten aus dem Leben mit Griseldis Wenner und Axel Bulthaupt',
'14912798':'Unter unserem Himmel',
'7545068':'Das regionale Reise-Journal -  Zuhause ist es am schönsten – finden die Unterwegs-Moderatorinnen aus Sachsen, Thüringen und Sachsen-Anhalt. Und deshalb ist die Sendung eine Fundgrube für Leute, die in Mitteldeutschland neue Attraktionen, spannende Geschichten und pure Idylle erleben wollen. Entdeckungen, die nicht in jedem Reiseführer<br/>stehen.',
'21698418':'Uschi Dämmrich von Luttitz auf Entdeckungsreise in der bayerischen Vereinswelt: Pro Sendung nimmt die Moderatorin zwei Vereine unter die Lupe und versucht als "Mitglied auf Zeit" herauszufinden, was die Menschen im Verein vereint.',
'22380484':'Die neue Ensemble-Comedy-Show im WDR',

#V
'14913272':'Das Vaterunser verbindet rund 2,3 Milliarden Christen auf der ganzen Welt - Protestanten wie Katholiken, Orthodoxe wie Freikirchen.',
'439104':'Blut ist dicker als Wasser. Die Soap um Familie, Liebe und Leiden.',
'3280910':'Making-Ofs und Interviews.',
'2702262':'Jessicas Welt: Der \'Verbotene Liebe\'-Videoblog',
'14913840':'Kabarettist Mathias Tretter bittet zum "Bühnensport". Im Vereinsheim sorgen Newcomer für Überraschungen, Etablierte für Begeisterung und alle gemeinsam für einen unvergessenen Abend in lockerer Wirtshaus-Atmosphäre.',
'13491232':'?vernetzt ? verkuppelt ? verliebt? ist die Dating-Show für das digitale Zeitalter: Drei junge Menschen suchen für einen Single-Freund über soziale Netzwerke im Internet nach einem geeigneten Partner.',
'3583382':'Dokumentationsserie über das Leben auf einem Kreuzfahrtschiff.',
'437898':'Mit versteckter Kamera legt Guido Cantz Stars herein.',
'16104442':'',
'14913282':'Viele Wege führen in Bayern zu einer Hochschulzugangsberechtigung. Das zeigt die TV-Dokumentation "Viele Wege – ein Ziel. Fahrplan zur Hochschulreife".',
'22828172':'Ein Mord, eine Leiche und vier Verdächtige!',
'14049224':'Visite informiert jeden Dienstag über aktuelle Entwicklungen aus den Bereichen Medizin und Gesundheit - aus Klinik, Praxis und Forschung.',
'14913290':'Vom Ahorn bis zur Zwiebel',
'12882124':'Köstlichkeiten aus der Adelsküche',
'14912660':'',
'27720756':'Wiener Vorstadt. Bessere Gesellschaft. Schein und Sein. Ein goldener Käfig. Doch ist wirklich alles Gold, was glänzt?',
'27740386':'"Voss & Team" ist ein modernes Ombuds- und Verbraucherformat: emotional, unterhaltsam, hilfreich und frech. "Voss & Team" greift ein, wenn die Interessen von Verbrauchern, Arbeitnehmern, Mietern oder Patienten bedroht sind.',
'12882044':'Sternekoch Björn Freitag gibt handfeste Tipps für den Verbraucher und nie gesehene Einblicke in die Lebensmittelindustrie.',
'23022010':'Die ARD hat eines der größten Korrespondentennetze weltweit. Viele erzählenswerte Geschichten "schaffen" es aber nicht in die großen Sendungen. In ihren Videoblogs berichten unsere Korrespondenten über die kleinen Dinge des Lebens und die große Politik, über Ernstes und Skurriles, über besondere Rituale und alltägliche Gebräuche.',
'13376662':'Vom 25. bis 29.3. dreht sich beim SWR alles um die Krise in der Lebensmitte. Alle Sendungen zur Midlife Crisis, ob Dokumentationen, Spielfilme oder die Sendezeiten der Serie "Zeit der Helden", finden Sie in unserer Übersicht. Hier verpassen Sie keinen Termin.',

#W
'1026408':'',
'10535956':'"Fernsehen macht blöd - und unglaublich viel Spaß!" So begrüßt Philipp Walulis seine Zuschauer bei "Walulis sieht fern". In seiner Fernsehsatire zieht er alles durch den Kakao.',
'9273664':'feuilletonistisches Magazin aus dem ARD-Studio Warschau',
'26282956':'Die beiden Reporter Nina und Michael begeben sich auf eine Spurensuche der besonderen Art: Sie wollen wissen, wie sie zu dem Menschen geworden sind, der sie heute sind. In 12 Folgen geht es um das Thema Persönlichkeitsentwicklung.',
'3914816':'"was! – Wirtschaft, Arbeiten, Sparen" ist das rbb-Wirtschafts- und Verbrauchermagazin. Es wird von Gerald Meyer jeden zweiten Mittwoch um 22:15 Uhr im rbb Fernsehen präsentiert.',
'17573262':'Die 6-teilige Reihe erzählt von den vielen Versuchen der Menschen, die Zeit zu messen und einzuteilen - von Stonehenge über die römische Antike, die islamische und jüdische Zeitrechnung bis hin zum digitalen Ewigen Kalender.',
'14913300':'Wie kommt es zu Spontanheilungen? Wie erklärt sich die Wirkung von Musik? Warum müssen wir schlafen? Niemand kennt die endgültigen Antworten darauf. Die Fernsehserie "Was wir noch nicht wissen" ist eine faszinierende Reise durch die Welt der unbeantworteten Fragen aus Wissenschaft und Technik.',
'18198186':'Westdeutscher Rundfunk',
'12877260':'Der dokumentarische Blick über den Tellerrand',
'7293644':'Das kompakte Informationsmagazin für NRW',
'17834280':'Tom Buhrow diskutiert mit Publikum und Kritikern',
'12994200':'WDR extra - die Sondersendung der Aktuellen Stunde',
'7989132':'Die Auslandssendung im WDR',
'5439278':'Die Geschichte geht weiter. Während Martin Kupfer noch immer unter Albträumen wegen seiner geliebten Julia leidet, verliert sich sein Bruder Falk immer mehr in Hass und Einsamkeit.',
'23021314':'Reptile Comedy mit Michael Hatzius und seiner Echse.',
'3906326':'Die Weltbilder blicken Woche für Woche bis zum Horizont und weiter. Sie erzählen die wichtigen Geschichten aus dem Ausland: bildstark und informativ.',
'329478':'Der Weltspiegel als Video on Demand: Reportagen aus aller Welt.',
'14937890':'Wer bei der neuen EinsPlus-Gameshow gewinnen will, muss auf Zack sein: Tempo, Einfallsreichtum, Überzeugungskraft und Witz sind gefragt, denn nur "Wer\'s bringt, gewinnt"!',
'3682636':'Geschichte',
'13618368':'WESTART Jazzline präsentiert die vielseitige Bandbreite des Jazz im WDR Fernsehen.',
'13618372':'WESTART Klassik bündelt die große Vielfalt klassischer Musik und bewegenden Tanztheaters im WDR Fernsehen.',
'13618380':'WESTART Magazin ist das Kulturmagazin des WDR Fernsehens für Nordrhein-Westfalen – aktuell, lustvoll und abwechslungsreich.',
'13618376':'WESTART Meisterwerke – Die Galerie',
'13618364':'WESTART Talk – macht Lust auf Kultur!',
'12877276':'WESTPOL - das Politmagazin für NRW',
'7545404':'Die Wetterschau für Mitteldeutschland',
'338188':'Wie wird das Wetter? Die Videos zur Wettersendung im Ersten.',
'6027456':'Von Eltern und Kindern. Von Vätern und Töchtern.',
'4040724':'Eberhard Schilling, bekannter Moderator von SR 3 Saarlandwelle, zieht mit Kamera und Mikrophon als Realisator in die Städte und Dörfer, um auf schöne Schauplätze und interessante Menschen zu treffen.',
'14913362':'Wir in Bayern',
'8758698':'Wir in RP',
'14912842':'Moderne und Tradition sind keine Gegenpole. Bei den Wirtshausmusikanten, treffen Gamsbart auf Rastalocken oder Zwiefacher auf Samba und Rumba. Traudi Siferlinger und Wolfgang Binder präsentieren Tradimix der besonderen Art.',
'28104962':'Warum haben wir Angst vor Spinnen? Lässt sich der ökonomische Wert eines Badesees berechnen? Wieviel Prozent der Meerestiefen sind vom Menschen erforscht? Und sollten wir wirklich an die Existenz riesiger Kraken glauben? Antworten auf diese und weitere Fragen sucht Wissenschaftsjournalist und Moderator Karsten Schwanke mit Wissenschaftlerinnen und Wissenschaftlern, die er in sein Hausboot in Berlin einlädt.',
'1430':'Wissen ist keine Schande - sagen Shary und Ralph.',
'21155340':'Susanne Holst erklärt uns spannende Fakten rund um Gesundheit und den Körper.',
'15526316':'Thomas D. erklärt, wie wir unsere Umwelt schützen können.',
'11274520':'Vince Ebert präsentiert "Wissen vor acht - Werkstatt" und erklärt Dinge und Phänomene des Alltags.',
'11274512':'Anja Reschke präsentiert "Wissen vor acht - Zukunft". Wie wird uns Technik künftig beeinflussen?',
'32396932':'Der spannenden Frage, wo unser Wetter eigentlich entsteht, geht Wetter-Moderator Sven Plöger in einer zweiteiligen Dokumentation nach.',
'17025702':'',
'7545372':'Das Magazin in sorbischer Sprache',
'12877292':'Freude am Reisen',
'8029410':'',
'427262':'Staunen, entdecken, verstehen - das bietet "W wie Wissen" immer samstags um 16:00 Uhr im Ersten - und danach als Video hier in der Mediathek.',
'9029008':'Dokuserie, deren Schauplatz die Tierrettungsstation Harnas am Rand der afrikanischen Kalahari-Wüste ist.',
'442936':'Kirche und Glaube im Ersten',
'3011224':'',
'3011232':'',
'13618360':'Die Show mit dem Hund',
'11140718':'Die einzige Show im deutschen Fernsehen, die von einem Hund moderiert wird!',
'16888632':'Die interaktive Late Night zur Bundestagswahl',

#X

#Y

#Z
'14950946':'Z\'am rocken - der interkulturelle Crossover aus Musik und Talk: Im Münchner Hofbräuhaus treffen sich junge Musiker aus Bayern und der ganzen Welt, um miteinander aufzuspielen. Dabei trifft Blasmusik auf Rap, Jodeln auf Elektro und Volksmusik auf Jazz. Mittendrin: Gastgeberin Luise Kinseher.',
'3714742':'Von Boulevardschlachten über Rosenkriege bis hin zu den Image-Kampagnen der Polit-Szene - Zapp blickt hinter die Kulissen der Medienwelt.',
'15397972':'Die Band "Zärtlichkeiten mit Freunden" lädt sich musikalische Gäste in ihren Oldtimer-Bus und begleitet sie auf dem Weg zu ihren Konzerten.',
'8502614':'Arnd Zeigler analysiert das Fußball-Geschehen auf ganz persönliche Weise.',
'14912690':'Zeit und Ewigkeit',
'3822084':'Magazin mit informativen und amüsanten Berichte über Land und Leute, Promis auf die Studio-Couch, umfassenden Serviceinformationen',
'7535548':'Zimmer frei! : Die prominente Wohngemeinschaft',
'19399052':'Die Sendung "Zoobabies" zeigt, wie die Tierbabys auf die Welt kommen, wachsen und groß werden.',
'14912832':'Zsammg\'spuit',
'610194':'Zur Sache BW!',
'6223218':'zur Sache RP!',
'14913712':'Spessart und Karwendel',
}



def toDesc(id):
	if dictId2Desc.has_key(id) and len(dictId2Desc[id]) >2:
		string = dictId2Desc[id]
		return string[0].upper()+string[1:]
	else:
		print '##### id '+id+' UNKNOWN desc'
		return ''